In [1]:
import numpy as np
import pandas as pd

import pickle

In [2]:
# read the dictionary of CIK codes
with open('CIK_year.txt', 'rb') as fp:
    CIK = pickle.load(fp)
    

# convert all CIK codes in the dictionary to strings
#for key, value in CIK.items():
#    CIK[key] = [str(cik) for cik in value]
            

# read the csv of data
data = pd.read_csv('data.csv') #, dtype={'Instrument': 'str'})

In [3]:
unique_CIKs = len(list(set(data.Instrument.to_list())))
print(unique_CIKs)
len(data.Instrument.unique())

15221

15221

In [4]:
# creat a list to add all CIK codes to
CIK_liste = []

# iterating over the dictionary items and add CIK lists to our list
for key, value in CIK.items():
    CIK_liste += value

# remove duplicated elements
CIK_list = list(set(CIK_liste))

print('There are', len(CIK_list), 'CIK codes in our list.')

CIK_list

There are 2107 CIK codes in our list.

[909326,
 40987,
 106532,
 1048620,
 90168,
 1441849,
 892986,
 1400891,
 1278027,
 1122380,
 1097805,
 1368147,
 933974,
 1319009,
 1065059,
 753772,
 1048685,
 1024109,
 32878,
 1343611,
 1024126,
 1065088,
 1130626,
 1097864,
 712843,
 1294476,
 106640,
 884887,
 1368218,
 1056923,
 73887,
 1015979,
 1138862,
 311471,
 1474735,
 1302707,
 909494,
 745655,
 57528,
 843964,
 786620,
 778438,
 319687,
 1368265,
 1073362,
 1130713,
 8411,
 1343719,
 893160,
 1433833,
 893162,
 1286382,
 1089775,
 82166,
 1114365,
 1581312,
 868611,
 1556739,
 1327364,
 1138951,
 1401106,
 1073429,
 1073431,
 1065246,
 737572,
 1163560,
 1573166,
 1057083,
 745788,
 74046,
 786765,
 1253710,
 1048911,
 1040719,
 1065298,
 1360214,
 819551,
 1376610,
 860518,
 1352045,
 1433966,
 1016177,
 1171825,
 901491,
 1065331,
 868725,
 1065332,
 1114483,
 1499505,
 49534,
 1450390,
 1081751,
 811419,
 827809,
 770471,
 1393066,
 1089976,
 1417663,
 98752,
 1466815,
 1024452,
 1401300,
 1016281,
 721371,
 1090012,
 909791,
 352747,
 1114605,
 778734,
 1376755,
 1311230,
 909832,
 926229,
 1409565,
 1098278,
 1376812,
 1565228,
 352825,
 885306,
 713275,
 311871,
 901696,
 1131072,
 885322,
 1098315,
 811596,
 795212,
 926295,
 1122904,
 852570,
 49754,
 1090159,
 1049210,
 25212,
 909950,
 1532543,
 107140,
 1614469,
 918160,
 1376912,
 877212,
 1163932,
 1122976,
 49826,
 1426082,
 1311396,
 320174,
 811696,
 1082038,
 1163958,
 352955,
 82628,
 1442505,
 1475273,
 1123028,
 1024725,
 819926,
 1065696,
 746210,
 885475,
 1082084,
 1016546,
 1000180,
 1385205,
 934648,
 1172222,
 99070,
 1065728,
 312065,
 1311486,
 107263,
 25354,
 1385228,
 713492,
 738076,
 1114908,
 852766,
 1377053,
 852772,
 1000229,
 1000234,
 877355,
 1114925,
 885551,
 1368883,
 1368900,
 1270597,
 852807,
 836429,
 1532750,
 1106773,
 320345,
 1549145,
 1000285,
 1049442,
 25445,
 1065837,
 918387,
 1090425,
 770944,
 820097,
 1065860,
 885639,
 1418135,
 926617,
 1057693,
 1049502,
 795551,
 353184,
 1106851,
 1000368,
 1237941,
 943034,
 1205181,
 1516479,
 1090507,
 353230,
 1393614,
 1385424,
 1360849,
 1090514,
 1057746,
 1434589,
 1393631,
 99302,
 1582054,
 812011,
 1287151,
 1123316,
 99321,
 58361,
 1434621,
 1106942,
 353278,
 1532930,
 91142,
 1410056,
 918541,
 1303565,
 820237,
 1336339,
 1385492,
 1287213,
 918581,
 1311803,
 320573,
 320575,
 1016900,
 1385542,
 1385543,
 1180743,
 1385544,
 17485,
 943184,
 820313,
 1016933,
 1041514,
 869487,
 1082484,
 1287286,
 1156216,
 1156218,
 1066107,
 58492,
 1156220,
 9342,
 1156221,
 902272,
 1410177,
 894081,
 1672326,
 902281,
 1082510,
 730255,
 1066134,
 730263,
 935063,
 42136,
 935066,
 869531,
 1131675,
 1262751,
 1582244,
 1123494,
 9389,
 1008817,
 722104,
 869561,
 1443002,
 910521,
 1082554,
 844985,
 1524931,
 1393861,
 1172678,
 1156295,
 1311953,
 943320,
 943322,
 1434842,
 58592,
 1336545,
 1172706,
 1058027,
 1058033,
 1443062,
 1000697,
 1541371,
 1074436,
 1058057,
 1164554,
 812301,
 1434893,
 1107216,
 1238289,
 34067,
 1123606,
 779544,
 927003,
 910619,
 353569,
 1156388,
 34088,
 1066281,
 1058090,
 1303849,
 910638,
 1099066,
 804154,
 1475899,
 910655,
 1123647,
 877890,
 34115,
 1017156,
 1508677,
 1312073,
 1107280,
 927066,
 943452,
 1410402,
 34151,
 877931,
 1394029,
 1172852,
 804212,
 820608,
 1107332,
 1041803,
 1050007,
 1115552,
 779681,
 1263011,
 1041829,
 1402281,
 1443242,
 918964,
 1164727,
 1377720,
 1328571,
 1549756,
 1295810,
 1041859,
 75208,
 722392,
 26076,
 1205727,
 1263074,
 919012,
 919013,
 804328,
 804331,
 1394156,
 1058290,
 353779,
 75252,
 943605,
 1058299,
 1402364,
 1377789,
 878079,
 1050112,
 1107457,
 1656328,
 1320461,
 714256,
 1230355,
 75288,
 894490,
 771617,
 83490,
 353827,
 894503,
 1623595,
 1181232,
 9779,
 837173,
 1050167,
 886328,
 26172,
 1418819,
 935493,
 1476170,
 1295947,
 75340,
 1410637,
 1386062,
 894544,
 1336917,
 1140310,
 1009244,
 91741,
 1091164,
 869986,
 1238631,
 1418862,
 1132143,
 1001082,
 919175,
 1017480,
 18061,
 1107601,
 353944,
 911002,
 1083036,
 853665,
 894627,
 812708,
 1025707,
 50863,
 1033905,
 1492658,
 1124024,
 919226,
 861884,
 1066684,
 1115836,
 853695,
 1279676,
 1750,
 1287900,
 927454,
 1009379,
 943861,
 1361658,
 18172,
 1083132,
 878334,
 9984,
 861955,
 1050377,
 50957,
 1328910,
 1353487,
 935703,
 722723,
 829224,
 935724,
 911149,
 1304366,
 911151,
 1361709,
 1394487,
 853816,
 1058623,
 10048,
 1173313,
 1034054,
 796486,
 1017673,
 1296205,
 18255,
 870228,
 1279831,
 1099609,
 1107802,
 837472,
 1304421,
 788329,
 812906,
 1075066,
 821130,
 804753,
 722839,
 771999,
 1025953,
 1083301,
 1066923,
 1329068,
 1451951,
 821189,
 763846,
 92103,
 1132487,
 1615817,
 1058767,
 1116112,
 1066961,
 853971,
 1001430,
 1443799,
 1009626,
 1533924,
 1320934,
 1173489,
 2034,
 1042418,
 1001463,
 845818,
 1058811,
 1361916,
 870398,
 714756,
 1075206,
 1296391,
 944136,
 1107978,
 1058828,
 1304588,
 1091596,
 1361937,
 1034258,
 747540,
 1271833,
 100378,
 919583,
 1329184,
 944163,
 1124394,
 1132590,
 763950,
 919603,
 313395,
 51253,
 919605,
 845879,
 886835,
 829499,
 34879,
 895041,
 1091667,
 1108058,
 796764,
 1132645,
 1476719,
 1116284,
 886912,
 2178,
 1271940,
 878731,
 1321099,
 1108109,
 1001614,
 1378453,
 895126,
 1018005,
 1042582,
 854171,
 26780,
 821407,
 84129,
 1419428,
 100517,
 1009829,
 1394855,
 1288359,
 1009833,
 1452206,
 92339,
 878774,
 1394872,
 1452217,
 43196,
 919742,
 1362120,
 1099977,
 1403085,
 878802,
 1296595,
 1509589,
 911576,
 1091801,
 878808,
 911583,
 772320,
 1009891,
 1173738,
 821483,
 1132784,
 813298,
 1026291,
 1018099,
 1026304,
 1313024,
 1124608,
 723209,
 1394954,
 1083663,
 944400,
 1091862,
 1067294,
 821536,
 1157408,
 911650,
 43300,
 1116463,
 1345840,
 928054,
 1419581,
 1370431,
 84290,
 1091907,
 1157443,
 878927,
 1534287,
 764241,
 354655,
 1108320,
 895329,
 870753,
 1042784,
 1042783,
 1452384,
 1116521,
 887150,
 739708,
 854398,
 1051009,
 1042825,
 944522,
 1157516,
 805264,
 1173924,
 1010086,
 870826,
 723371,
 1100202,
 1092013,
 1001903,
 1345968,
 1370544,
 2488,
 911801,
 805305,
 895419,
 2491,
 1452476,
 1575360,
 1124804,
 1329605,
 1141197,
 1092050,
 936402,
 100826,
 1436126,
 862692,
 1354217,
 1051114,
 1100270,
 797167,
 748015,
 1092083,
 788983,
 18937,
 1436164,
 100885,
 1116694,
 895516,
 1337885,
 76321,
 1362468,
 1288741,
 739878,
 1403431,
 1403433,
 10795,
 68145,
 813621,
 1444406,
 1436222,
 1002047,
 1550910,
 1321544,
 731727,
 920148,
 944725,
 1362516,
 1165921,
 944739,
 830052,
 84581,
 1509991,
 1010286,
 1043055,
 928375,
 944765,
 1477246,
 1084031,
 1297024,
 1157762,
 887433,
 862861,
 797329,
 354963,
 797331,
 1141395,
 1157780,
 1387156,
 895642,
 895648,
 928421,
 1108645,
 895655,
 1436329,
 944809,
 854701,
 1346222,
 1321646,
 1575599,
 1067701,
 854709,
 1362614,
 1125052,
 912061,
 1002178,
 879303,
 1084103,
 101063,
 887497,
 355019,
 1133260,
 1092302,
 731859,
 1043156,
 813781,
 19161,
 912093,
 51939,
 1362659,
 821995,
 1338095,
 895728,
 1288946,
 1051379,
 854775,
 1108730,
 920321,
 1403651,
 813828,
 797448,
 1239819,
 1133324,
 1116942,
 854800,
 314132,
 1272597,
 1411861,
 27419,
 797468,
 1207070,
 887596,
 1166126,
 1100592,
 707388,
 1190723,
 1518403,
 1018693,
 1018710,
 1059677,
 813920,
 1051488,
 1018724,
 84839,
 879465,
 789356,
 912241,
 1010552,
 1051512,
 764794,
 863110,
 1100682,
 1125259,
 904080,
 928659,
 2969,
 19353,
 1403802,
 1125276,
 1379246,
 101295,
 1010610,
 1059763,
 1043382,
 1133494,
 84919,
 11199,
 1403853,
 1166291,
 1108951,
 723928,
 1346526,
 879585,
 764897,
 1076195,
 216039,
 1108967,
 912365,
 814068,
 76791,
 1018871,
 1092605,
 1272830,
 1174527,
 1035267,
 1035270,
 1526796,
 1403922,
 1002517,
 1002520,
 797721,
 846876,
 355356,
 1166365,
 928800,
 3116,
 1166380,
 1043509,
 1084475,
 1387580,
 1018946,
 855109,
 1256536,
 68709,
 1100917,
 1346685,
 19584,
 912513,
 1084557,
 855182,
 1690769,
 1305748,
 1551510,
 1289370,
 912544,
 887969,
 1109153,
 1330340,
 1100969,
 1060009,
 879796,
 1100981,
 1133754,
 1387713,
 1109189,
 806085,
 1092807,
 863436,
 863437,
 1109196,
 912607,
 863456,
 1092839,
 1076462,
 314606,
 929008,
 1158387,
 1289460,
 60667,
 1412347,
 27904,
 896262,
 896264,
 1289480,
 93456,
 1117458,
 757011,
 19731,
 830741,
 814361,
 945436,
 1314077,
 1084702,
 1109279,
 355627,
 109870,
 1396016,
 1330487,
 27960,
 1297720,
 1002822,
 1477961,
 855372,
 1568079,
 1084752,
 945489,
 1051985,
 912728,
 314712,
 27996,
 77155,
 1232229,
 93542,
 77159,
 912750,
 1101169,
 920947,
 814453,
 740726,
 929144,
 1355128,
 912767,
 1060232,
 52617,
 1437073,
 1363346,
 1002902,
 19871,
 85408,
 863650,
 1346980,
 1387942,
 85417,
 789933,
 896429,
 1494448,
 60849,
 1437106,
 1379763,
 880059,
 101821,
 1134016,
 355777,
 912833,
 1322439,
 1043914,
 1265107,
 773588,
 1084887,
 1093082,
 822746,
 1076700,
 1019361,
 773603,
 945641,
 912875,
 896493,
 28146,
 1175028,
 814586,
 1052163,
 912908,
 1003022,
 1404438,
 1453593,
 855581,
 855585,
 822818,
 1076770,
 945699,
 1060390,
 749098,
 60977,
 1035826,
 1396279,
 1379895,
 52795,
 1289790,
 1084991,
 1379905,
 1175108,
 1338949,
 1060426,
 814676,
 1093207,
 1011290,
 724571,
 1347178,
 1011308,
 896622,
 1674862,
 855667,
 1068660,
 1027702,
 913015,
 724606,
 77449,
 880266,
 1232524,
 1289871,
 102037,
 1093273,
 1330849,
 1388195,
 77476,
 1339048,
 716457,
 1404592,
 945841,
 1224370,
 888507,
 ...]

In [5]:
len(CIK_liste)

16445

In [7]:
# drop non-quantitative columns
data_cl = data.drop(columns=['NAICS Industry Group Name', 'Delisted Quote Flag', 'Company Common Name',
                                    'CIK Number', 'Instrument Is Active Flag', 'Bankrupt'])
# check on the data shape
print(data_cl.shape)

data_cl.head()

(345740, 23)

,Instrument,Total Debt,Accounts Payable (CF),Inventories (CF),Retained Earnings (Accumulated Deficit),Net Debt Incl. Pref.Stock & Min.Interest,Total Current Assets,Total Liabilities,Total Equity,Tangible Book Value - Banks,...,Cash and Short Term Investments,Market Value for Company,Tangible Book Value Per Share,Net Sales,Operating Income,Tangible Book Value - Utility,"Total Assets, Reported",Depreciation And Amortization,Total Current Liabilities,Year
0,910655,1866000.0,-235000.0,-9289000.0,49741000.0,-8580000.0,8.268900e+07,2.325000e+07,9.448900e+07,8.712400e+07,...,10446000.0,195540000.0,8.43993,3.603260e+08,40075000.0,8.712400e+07,1.177390e+08,413000.0,1.920900e+07,2000
1,1116521,10000000.0,-47000000.0,81000000.0,NaN,-184000000.0,3.043000e+09,2.422000e+09,1.817000e+09,1.556000e+09,...,194000000.0,NaN,5.59129,8.268000e+09,369000000.0,1.556000e+09,4.239000e+09,NaN,1.597000e+09,2000
2,895651,377000.0,NaN,289000.0,-18251000.0,-1483000.0,9.479000e+06,1.318600e+07,1.895900e+07,3.622000e+06,...,1860000.0,NaN,0.40670,5.497100e+07,-1056000.0,3.622000e+06,3.214500e+07,NaN,6.303000e+06,2000
3,1398702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000
4,1434621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000

In [8]:
# check data format for CIK codes in df and dict
print(type(data_cl.Instrument[1]))
type(CIK_list[1])

<class 'numpy.int64'>

int

In [9]:
# drop the all companies but the ones in the CIK list
data_cl = data_cl[data_cl.Instrument.isin(CIK_list)]

print('Data df shape:', data_cl.shape, '\n')

print('If every thing is okay, then the number of unique CIK in semi-clean data,', len(data_cl.Instrument.unique()),
      '\nshould be equal to the number of CIK codes in the dictionary:', len(CIK_list))

print()
print('Is that true?')
print(str(len(data_cl.Instrument.unique()) == len(CIK_list)) + '!')


data_cl.head()

Data df shape: (59360, 23)

If every thing is okay, then the number of unique CIK in semi-clean data, 2107
should be equal to the number of CIK codes in the dictionary: 2107

Is that true?
True!

,Instrument,Total Debt,Accounts Payable (CF),Inventories (CF),Retained Earnings (Accumulated Deficit),Net Debt Incl. Pref.Stock & Min.Interest,Total Current Assets,Total Liabilities,Total Equity,Tangible Book Value - Banks,...,Cash and Short Term Investments,Market Value for Company,Tangible Book Value Per Share,Net Sales,Operating Income,Tangible Book Value - Utility,"Total Assets, Reported",Depreciation And Amortization,Total Current Liabilities,Year
0,910655,1866000.0,-235000.0,-9289000.0,49741000.0,-8580000.0,8.268900e+07,2.325000e+07,9.448900e+07,8.712400e+07,...,10446000.0,195540000.0,8.43993,3.603260e+08,40075000.0,8.712400e+07,1.177390e+08,413000.0,1.920900e+07,2000
1,1116521,10000000.0,-47000000.0,81000000.0,NaN,-184000000.0,3.043000e+09,2.422000e+09,1.817000e+09,1.556000e+09,...,194000000.0,NaN,5.59129,8.268000e+09,369000000.0,1.556000e+09,4.239000e+09,NaN,1.597000e+09,2000
3,1398702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000
4,1434621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000
5,1367311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000

In [10]:
data.describe()

,Instrument,Total Debt,Accounts Payable (CF),Inventories (CF),Delisted Quote Flag,Retained Earnings (Accumulated Deficit),Net Debt Incl. Pref.Stock & Min.Interest,Total Current Assets,Total Liabilities,CIK Number,...,Tangible Book Value Per Share,Net Sales,Operating Income,Instrument Is Active Flag,Tangible Book Value - Utility,"Total Assets, Reported",Depreciation And Amortization,Total Current Liabilities,Year,Bankrupt
count,3.457400e+05,2.158840e+05,1.182840e+05,1.114090e+05,282160.000000,2.097270e+05,1.935600e+05,1.799540e+05,2.161350e+05,3.387200e+05,...,2.149320e+05,1.789720e+05,2.071780e+05,282200.000000,2.158790e+05,2.176100e+05,1.029780e+05,1.799780e+05,345740.00000,345740.000000
mean,1.091527e+06,4.277239e+10,1.529308e+08,-3.197758e+08,0.390559,2.281466e+10,1.898458e+10,2.077694e+10,1.483424e+11,1.100851e+06,...,5.193646e+04,3.990665e+10,5.676744e+09,0.573707,2.915024e+10,1.806256e+11,4.993227e+09,1.716495e+10,2009.50000,0.069995
std,4.301466e+05,1.148630e+12,2.117028e+10,2.461518e+10,0.487876,6.934468e+11,5.836948e+11,5.073234e+11,4.706048e+12,4.246863e+05,...,5.357015e+06,1.077388e+12,2.713924e+11,0.494538,8.434227e+11,5.238838e+12,1.967775e+11,4.281344e+11,5.76629,0.255139
min,2.000000e+01,-3.500000e+04,-2.202808e+12,-3.518927e+12,0.000000,-2.066797e+12,-9.700831e+12,-2.866700e+07,-2.744270e+08,2.000000e+01,...,-3.467300e+08,-1.653913e+09,-2.798073e+12,0.000000,-4.427527e+12,-1.000000e+03,-3.290500e+10,0.000000e+00,2000.00000,0.000000
25%,8.839750e+05,1.794450e+05,-8.220200e+05,-5.439000e+06,0.000000,-5.789800e+07,-5.379335e+06,7.059000e+06,9.241700e+06,8.872268e+05,...,-9.830000e-03,9.129000e+06,-5.034105e+06,0.000000,-2.385800e+05,2.446200e+07,4.690000e+05,4.345210e+06,2004.75000,0.000000
50%,1.109196e+06,1.581364e+07,1.100000e+05,-1.757900e+05,0.000000,-3.149000e+06,3.861330e+06,5.967000e+07,1.010060e+08,1.122940e+06,...,2.010640e+00,1.047275e+08,4.640000e+05,1.000000,2.935500e+07,2.285040e+08,6.590000e+06,2.890600e+07,2009.50000,0.000000
75%,1.414374e+06,3.170210e+08,2.932528e+06,7.474200e+05,1.000000,8.233700e+07,2.153145e+08,3.294260e+08,9.147590e+08,1.415305e+06,...,8.734090e+00,7.141120e+08,5.379825e+07,1.000000,2.211270e+08,1.433203e+09,5.376250e+07,1.934390e+08,2014.25000,0.000000
max,1.782354e+06,8.252555e+13,2.318922e+12,3.344506e+12,1.000000,8.489600e+13,6.284471e+13,4.791200e+13,4.027469e+14,1.789215e+06,...,5.521000e+08,1.282560e+14,4.393300e+13,1.000000,8.918300e+13,4.367856e+14,2.044600e+13,4.537600e+13,2019.00000,1.000000

In [11]:
data_cl.describe()

,Instrument,Total Debt,Accounts Payable (CF),Inventories (CF),Retained Earnings (Accumulated Deficit),Net Debt Incl. Pref.Stock & Min.Interest,Total Current Assets,Total Liabilities,Total Equity,Tangible Book Value - Banks,...,Cash and Short Term Investments,Market Value for Company,Tangible Book Value Per Share,Net Sales,Operating Income,Tangible Book Value - Utility,"Total Assets, Reported",Depreciation And Amortization,Total Current Liabilities,Year
count,5.936000e+04,4.487900e+04,3.268700e+04,3.277400e+04,4.426800e+04,4.309700e+04,4.214500e+04,4.493400e+04,4.506000e+04,4.491200e+04,...,4.310000e+04,3.809000e+04,4.479000e+04,4.238100e+04,4.432400e+04,4.491200e+04,4.503800e+04,2.861300e+04,4.218400e+04,59360.00000
mean,9.586792e+05,6.635716e+09,1.223340e+08,-7.974437e+07,7.238084e+09,4.494782e+09,6.901693e+09,1.725604e+10,1.420701e+10,1.329362e+10,...,2.877748e+09,4.010478e+10,9.755258e+04,1.756743e+10,4.032503e+09,1.329362e+10,3.143123e+10,2.189297e+08,5.061362e+09,2009.50000
std,4.100406e+05,4.616500e+11,2.163993e+10,6.545597e+09,4.501854e+11,3.812525e+11,3.329516e+11,8.591853e+11,7.683743e+11,7.442757e+11,...,1.474839e+11,2.194970e+12,8.897990e+06,8.710213e+11,2.503758e+11,7.442757e+11,1.595436e+12,4.412849e+09,2.547779e+11,5.76633
min,1.750000e+03,0.000000e+00,-2.202808e+12,-5.618460e+11,-6.938070e+10,-9.700831e+12,0.000000e+00,-1.350200e+07,-3.709400e+10,-7.194400e+10,...,0.000000e+00,0.000000e+00,-2.070000e+08,-1.977210e+06,-2.719973e+11,-7.194400e+10,-1.000000e+03,-2.961000e+06,0.000000e+00,2000.00000
25%,8.299138e+05,1.708500e+06,-1.533000e+06,-4.497000e+06,-1.088890e+08,-2.553000e+06,1.049900e+07,1.494825e+07,2.269000e+06,-6.110375e+06,...,1.720750e+06,4.132500e+06,-3.720900e-01,1.546300e+07,-1.113800e+07,-6.110375e+06,2.925250e+07,8.010000e+05,8.220250e+06,2004.75000
50%,1.038146e+06,3.174300e+07,1.220000e+05,-1.240000e+05,-1.357358e+07,1.357300e+07,7.591000e+07,1.174935e+08,5.155400e+07,1.549750e+07,...,1.400300e+07,8.175000e+07,1.138735e+00,1.599900e+08,-7.000000e+04,1.549750e+07,2.264505e+08,6.547000e+06,4.402532e+07,2009.50000
75%,1.275712e+06,3.500000e+08,3.455500e+06,1.031500e+06,6.783100e+07,2.579520e+08,3.480560e+08,8.391718e+08,3.391672e+08,1.568360e+08,...,8.289650e+07,7.311175e+08,6.749180e+00,8.875870e+08,4.318900e+07,1.568360e+08,1.255125e+09,4.546600e+07,2.182952e+08,2014.25000
max,1.735828e+06,5.322334e+13,2.318922e+12,6.108430e+11,5.249701e+13,4.730523e+13,2.872716e+13,7.963924e+13,7.111920e+13,7.111920e+13,...,1.377761e+13,2.244971e+14,5.521000e+08,7.042871e+13,2.587298e+13,7.111920e+13,1.324280e+14,3.800370e+11,2.313373e+13,2019.00000

In [12]:
# just checking...
data_cl.sort_values(by=['Instrument', 'Year'])

,Instrument,Total Debt,Accounts Payable (CF),Inventories (CF),Retained Earnings (Accumulated Deficit),Net Debt Incl. Pref.Stock & Min.Interest,Total Current Assets,Total Liabilities,Total Equity,Tangible Book Value - Banks,...,Cash and Short Term Investments,Market Value for Company,Tangible Book Value Per Share,Net Sales,Operating Income,Tangible Book Value - Utility,"Total Assets, Reported",Depreciation And Amortization,Total Current Liabilities,Year
24200,1750,1.813590e+08,24659000.0,-46212000.0,184529000.0,1.731090e+08,5.081860e+08,4.005950e+08,326035000.0,285942000.0,...,8250000.0,4.812300e+08,10.44308,1.050608e+09,77381000.0,285942000.0,7.266300e+08,NaN,173586000.0,2000
40277,1750,2.067610e+08,-21536000.0,-6644000.0,210474000.0,2.055200e+08,5.112670e+08,4.014830e+08,336494000.0,297654000.0,...,1241000.0,3.390600e+08,11.07962,1.024333e+09,70658000.0,297654000.0,7.379770e+08,NaN,163816000.0,2001
56354,1750,1.936390e+08,-35034000.0,17887000.0,219848000.0,1.798300e+08,4.781230e+08,3.616420e+08,340212000.0,294837000.0,...,13809000.0,2.420000e+08,10.94543,8.742550e+08,40390000.0,294837000.0,7.018540e+08,NaN,125392000.0,2002
72431,1750,2.602240e+08,-25261000.0,-31749000.0,156479000.0,2.257020e+08,4.366560e+08,3.999640e+08,310235000.0,264329000.0,...,34522000.0,1.640000e+08,8.29398,6.387210e+08,-81289000.0,264329000.0,7.101990e+08,NaN,150464000.0,2003
88508,1750,2.569140e+08,-2841000.0,17755000.0,143272000.0,2.277600e+08,3.964120e+08,3.916330e+08,294988000.0,249037000.0,...,29154000.0,4.790900e+08,7.81881,5.998420e+08,908000.0,249037000.0,6.866210e+08,NaN,203575000.0,2004
104585,1750,2.520580e+08,6642000.0,15602000.0,146776000.0,2.183610e+08,4.322040e+08,4.076080e+08,301684000.0,257263000.0,...,33697000.0,4.389800e+08,7.97838,6.444690e+08,20281000.0,257263000.0,7.092920e+08,NaN,131261000.0,2005
120662,1750,2.309040e+08,19244000.0,-12013000.0,162229000.0,1.903960e+08,4.745420e+08,4.174860e+08,314744000.0,270328000.0,...,40508000.0,8.022800e+08,8.29583,7.404270e+08,38479000.0,270328000.0,7.322300e+08,NaN,160025000.0,2006
136739,1750,3.208650e+08,19735000.0,-58297000.0,197392000.0,1.991270e+08,6.244540e+08,5.561020e+08,422717000.0,378285000.0,...,121738000.0,1.079330e+09,10.32043,8.855180e+08,61279000.0,378285000.0,9.788190e+08,NaN,187788000.0,2007
152816,1750,3.278560e+08,6473000.0,-8567000.0,256052000.0,2.445390e+08,6.457210e+08,5.733900e+08,494243000.0,419976000.0,...,83317000.0,1.442020e+09,11.13138,1.061169e+09,98293000.0,419976000.0,1.067633e+09,NaN,256506000.0,2008
168893,1750,5.309120e+08,-26078000.0,-42339000.0,331196000.0,4.215210e+08,7.834310e+08,7.767550e+08,585255000.0,454089000.0,...,109391000.0,7.119100e+08,11.71147,1.384919e+09,132478000.0,454089000.0,1.362010e+09,NaN,218499000.0,2009
184970,1750,3.918090e+08,2651000.0,-45414000.0,374659000.0,2.793040e+08,8.513120e+08,6.791710e+08,696734000.0,545739000.0,...,112505000.0,8.946500e+08,14.03505,1.380529e+09,121313000.0,545739000.0,1.375905e+09,NaN,254418000.0,2010
201047,1750,4.370240e+08,-1474000.0,19015000.0,419287000.0,3.570980e+08,8.463310e+08,7.532750e+08,746906000.0,556021000.0,...,79370000.0,1.141510e+09,14.08219,1.352151e+09,91225000.0,556021000.0,1.500181e+09,NaN,324689000.0,2011
217124,1750,4.438770e+08,48700000.0,-13000000.0,486130000.0,3.858880e+08,9.139850e+08,8.678820e+08,835845000.0,654748000.0,...,57433000.0,7.722300e+08,16.45881,1.805112e+09,133725000.0,654748000.0,1.703727e+09,NaN,416010000.0,2012
233201,1750,7.922000e+08,18300000.0,-47600000.0,541800000.0,7.259000e+08,1.063300e+09,1.331100e+09,864600000.0,447000000.0,...,67700000.0,7.415000e+08,11.09929,2.065000e+09,130000000.0,447000000.0,2.195700e+09,NaN,473200000.0,2013
249278,1750,7.086000e+08,-50700000.0,16100000.0,584900000.0,6.342000e+08,1.033700e+09,1.218300e+09,918600000.0,505200000.0,...,75300000.0,1.109210e+09,12.82813,1.807900e+09,101900000.0,505200000.0,2.136900e+09,NaN,389000000.0,2014
265355,1750,6.340000e+08,26000000.0,-26000000.0,646000000.0,5.460000e+08,1.111400e+09,1.194500e+09,999500000.0,572400000.0,...,89200000.0,1.105390e+09,14.46907,1.709100e+09,125600000.0,572400000.0,2.194000e+09,NaN,402100000.0,2015
281432,1750,1.514000e+08,3900000.0,-32200000.0,644300000.0,9.670000e+07,8.958000e+08,6.090000e+08,845100000.0,684900000.0,...,54700000.0,9.213000e+08,19.33496,1.621400e+09,-86300000.0,684900000.0,1.454100e+09,NaN,412000000.0,2016
297509,1750,1.481000e+08,19400000.0,-26400000.0,681600000.0,1.169000e+08,8.817000e+08,5.902000e+08,865800000.0,712700000.0,...,31200000.0,1.134570e+09,20.64926,1.525400e+09,75100000.0,712700000.0,1.456000e+09,NaN,341400000.0,2017
313586,1750,1.573000e+08,19600000.0,-23300000.0,727900000.0,1.470000e+08,8.885000e+08,5.899000e+08,914200000.0,766000000.0,...,10300000.0,1.364520e+09,22.29696,1.590800e+09,82300000.0,766000000.0,1.504100e+09,NaN,335100000.0,2018
329663,1750,1.772000e+08,1800000.0,-25800000.0,733200000.0,1.461000e+08,9.427000e+08,5.884000e+08,936300000.0,789800000.0,...,31100000.0,1.310450e+09,22.75057,1.748300e+09,86000000.0,789800000.0,1.524700e+09,NaN,333300000.0,2019
208,2034,1.050000e+06,501000.0,-2481000.0,31224000.0,-9.618000e+06,6.996100e+07,2.142700e+07,64732000.0,61468000.0,...,11418000.0,6.805000e+07,2.83864,1.697250e+08,7411000.0,61468000.0,8.615900e+07,NaN,20502000.0,2000
24217,2034,1.050000e+06,501000.0,-2481000.0,31224000.0,-9.618000e+06,6.996100e+07,2.142700e+07,64732000.0,61468000.0,...,11418000.0,6.805000e+07,2.83864,1.697250e+08,7411000.0,61468000.0,8.615900e+07,NaN,20502000.0,2000
1418,2034,1.550000e+06,-184000.0,-3505000.0,35697000.0,-3.414000e+06,7.383900e+07,2.447700e+07,63604000.0,59137000.0,...,4964000.0,5.431000e+07,2.90354,1.853080e+08,9173000.0,59137000.0,8.808100e+07,NaN,23569000.0,2001
40294,2034,1.550000e+06,-184000.0,-3505000.0,35697000.0,-3.414000e+06,7.383900e+07,2.447700e+07,63604000.0,59137000.0,...,4964000.0,5.431000e+07,2.90354,1.853080e+08,9173000.0,59137000.0,8.808100e+07,NaN,23569000.0,2001
2628,2034,1.224500e+07,1455000.0,6280000.0,38006000.0,3.947000e+06,9.055800e+07,3.597000e+07,69203000.0,58836000.0,...,8298000.0,6.783000e+07,2.68045,1.781540e+08,5856000.0,58836000.0,1.051730e+08,NaN,35299000.0,2002
56371,2034,1.224500e+07,1455000.0,6280000.0,38006000.0,3.947000e+06,9.055800e+07,3.597000e+07,69203000.0,58836000.0,...,8298000.0,6.783000e+07,2.68045,1.781540e+08,5856000.0,58836000.0,1.051730e+08,NaN,35299000.0,2002
3838,2034,7.608000e+06,4174000.0,694000.0,40863000.0,-7.967000e+06,1.007240e+08,4.241300e+07,73290000.0,63469000.0,...,15575000.0,1.042400e+08,2.87098,2.293290e+08,7336000.0,63469000.0,1.157030e+08,NaN,42413000.0,2003
72448,2034,7.608000e+06,4174000.0,694000.0,40863000.0,-7.967000e+06,1.007240e+08,4.241300e+07,73290000.0,63469000.0,...,15575000.0,1.042400e+08,2.87098,2.293290e+08,7336000.0,63469000.0,1.157030e+08,NaN,42413000.0,2003
5048,2034,3.286000e+06,2907000.0,-4597000.0,46142000.0,-1.785400e+07,1.101150e+08,3.895000e+07,84569000.0,76374000.0,...,21140000.0,2.651600e+08,3.27138,2.699610e+08,13027000.0,76374000.0,1.235190e+08,NaN,38950000.0,2004
88525,2034,3.286000e+06,2907000.0,-4597000.0,46142000.0,-1.785400e+07,1.101150e+08,3.895000e+07,84569000.0,76374000.0,...,21140000.0,2.651600e+08,3.27138,2.699610e+08,13027000.0,76374000.0,1.235190e+08,NaN,38950000.0,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6464,1735828,2.000000e+06,-268000.0,NaN,NaN,1.243000e+06,6.568000e+06,6.769000e+06,12022000.0,12010000.0,...,769000.0,NaN,1.26569,1.494300e+07,7423000.0,12010000.0,1.879200e+07,883000.0,4897000.0,2005
117387,1735828,2.000000e+06,-268000.0,NaN,NaN,1.243000e+06,6.568000e+06,6.769000e+06,12022000.0,12010000.0,...,769000.0,NaN,1.26569,1.494300e+07,7423000.0,12010000.0,1.879200e+07,883000.0,4897000.0,2005
7674,1735828,6.719000e+07,590000.0,NaN,NaN,6.524500e+07,8.272000e+06,7.703400e+07,9909000.0,9899000.0,...,1955000.0,NaN,1.04322,2.554300e+07,13866000.0,9899000.0,8.694300e+07,2291000.0,4563000.0,2006
133464,1735828,6.719000e+07,590000.0,NaN,NaN,6.524500e+07,8.272000e+06,7.703400e+07,9909000.0,9899000.0,...,1955000.0,NaN,1.04322,2.554300e+07,13866000.0,9899000.0,8.694300e+07,2291000.0,4563000.0,2006
8884,1735828,6.719000e+07,590000.0,NaN,NaN,6.524500e+07,8.272000e+06,7.703400e+07,9909000.0,9899000.0,...,1955000.0,NaN,1.04322,2.554300e+07,13866000.0,9899000.0,8.694300e+07,2291000.0,4563000.0,2007
149541,1735828,6.719000e+07,590000.0,NaN,NaN,6.524500e+07,8.272000e+06,7.703400e+07,9909000.0,9899000.0,...,1955000.0,NaN,1.04322,2.554300e+07,13866000.0,9899000.0,8.694300e+07,2291000.0,4563000.0,2007
10094,1735828,1.158000e+08,3753000.0,NaN,NaN,1.148740e+08,1.822100e+07,1.345810e+08,138789000.0,131932000.0,...,1062000.0,6.149800e+08,7.17208,5.979700e+07,1872000.0,131932000.0,2.733690e+08,18395000.0,10835000.0,2008
165618,1735828,1.158000e+08,3753000.0,NaN,NaN,1.148740e+08,1.822100e+07,1.345810e+08,138789000.0,131932000.0,...,1062000.0,6.149800e+08,7.17208,5.979700e+07,1872000.0,131932000.0,2.733690e+08,18395000.0,10835000.0,2008
11304,1735828,1.100000e+08,-611000.0,NaN,NaN,1.004630e+08,3.355800e+07,2.258480e+08,255730000.0,249512000.0,...,9604000.0,2.893000e+08,8.40932,1.122360e+08,36680000.0,249512000.0,4.815780e+08,28415000.0,43457000.0,2009
181695,1735828,1.100000e+08,-611000.0,NaN,NaN,1.004630e+08,3.355800e+07,2.258480e+08,255730000.0,249512000.0,...,9604000.0,2.893000e+08,8.40932,1.122360e+08,36680000.0,249512000.0,4.815780e+08,28415000.0,43457000.0,2009
12514,1735828,2.820000e+08,3630000.0,NaN,NaN,2.796940e+08,8.093700e+07,4.024390e+08,380633000.0,375990000.0,...,2500000.0,6.862000e+08,12.10945,2.154240e+08,-1556000.0,375990000.0,7.830720e+08,63324000.0,56032000.0,2010
197772,1735828,2.820000e+08,3630000.0,NaN,NaN,2.796940e+08,8.093700e+07,4.024390e+08,380633000.0,375990000.0,...,2500000.0,6.862000e+08,12.10945,2.154240e+08,-1556000.0,375990000.0,7.830720e+08,63324000.0,56032000.0,2010
13724,1735828,2.370000e+08,-4370000.0,NaN,NaN,2.328160e+08,4.961100e+07,3.748330e+08,278660000.0,273589000.0,...,4217000.0,1.249550e+09,7.84362,1.372790e+08,-3530000.0,273589000.0,6.534930e+08,58763000.0,54226000.0,2011
213849,1735828,2.370000e+08,-4370000.0,NaN,NaN,2.328160e+08,4.961100e+07,3.748330e+08,278660000.0,273589000.0,...,4217000.0,1.249550e+09,7.84362,1.372790e+08,-3530000.0,273589000.0,6.534930e+08,58763000.0,54226000.0,2011
14934,1735828,3.250000e+08,-949000.0,NaN,NaN,3.215990e+08,5.059800e+07,5.176870e+08,391739000.0,387174000.0,...,3478000.0,1.331810e+09,8.89467,2.163890e+08,38315000.0,387174000.0,9.094260e+08,62894000.0,72955000.0,2012
229926,1735828,3.250000e+08,-949000.0,NaN,NaN,3.215990e+08,5.059800e+07,5.176870e+08,391739000.0,387174000.0,...,3478000.0,1.331810e+09,8.89467,2.163890e+08,38315000.0,387174000.0,9.094260e+08,62894000.0,72955000.0,2012
16144,1735828,3.370000e+08,2655000.0,NaN,NaN,3.339200e+08,5.978500e+07,5.551530e+08,488335000.0,484281000.0,...,3151000.0,1.351820e+09,10.13105,3.368850e+08,84495000.0,484281000.0,1.043488e+09,88178000.0,97450000.0,2013
246003,1735828,3.370000e+08,2655000.0,NaN,NaN,3.339200e+08,5.978500e+07,5.551530e+08,488335000.0,484281000.0,...,3151000.0,1.351820e+09,10.13105,3.368850e+08,84495000.0,484281000.0,1.043488e+09,88178000.0,97450000.0,2013
17354,1735828,7.758380e+08,-1464000.0,NaN,NaN,7.724260e+08,8.791000e+07,1.019719e+09,670280000.0,666697000.0,...,3509000.0,1.619580e+09,11.68845,3.464600e+08,51491000.0,666697000.0,1.689999e+09,102144000.0,103723000.0,2014
262080,1735828,7.758380e+08,-1464000.0,NaN,NaN,7.724260e+08,8.791000e+07,1.019719e+09,670280000.0,666697000.0,...,3509000.0,1.619580e+09,11.68845,3.464600e+08,51491000.0,666697000.0,1.689999e+09,102144000.0,103723000.0,2014
18564,1735828,8.786930e+08,4194000.0,NaN,NaN,8.761830e+08,7.469900e+07,1.149437e+09,510396000.0,507330000.0,...,2584000.0,7.905600e+08,8.85701,4.854890e+08,27644000.0,507330000.0,1.659833e+09,158415000.0,93890000.0,2015
278157,1735828,8.786930e+08,4194000.0,NaN,NaN,8.761830e+08,7.469900e+07,1.149437e+09,510396000.0,507330000.0,...,2584000.0,7.905600e+08,8.85701,4.854890e+08,27644000.0,507330000.0,1.659833e+09,158415000.0,93890000.0,2015
19774,1735828,9.388760e+08,-3228000.0,NaN,NaN,1.167657e+09,1.922540e+08,1.261401e+09,637205000.0,405191000.0,...,725000.0,1.216300e+08,5.87994,5.322990e+08,-356937000.0,405191000.0,1.898606e+09,173686000.0,97576000.0,2016
294234,1735828,9.388760e+08,-3228000.0,NaN,NaN,1.167657e+09,1.922540e+08,1.261401e+09,637205000.0,405191000.0,...,725000.0,1.216300e+08,5.87994,5.322990e+08,-356937000.0,405191000.0,1.898606e+09,173686000.0,97576000.0,2016
20984,1735828,1.427614e+09,10794000.0,NaN,NaN,1.654928e+09,1.294590e+08,1.792797e+09,-179677000.0,-411061000.0,...,2006000.0,1.538000e+08,-5.96173,3.387790e+08,-725697000.0,-411061000.0,1.613120e+09,177258000.0,81093000.0,2017
310311,1735828,1.427614e+09,10794000.0,NaN,NaN,1.654928e+09,1.294590e+08,1.792797e+09,-179677000.0,-411061000.0,...,2006000.0,1.538000e+08,-5.96173,3.387790e+08,-725697000.0,-411061000.0,1.613120e+09,177258000.0,81093000.0,2017
22194,1735828,1.161394e+09,-4489000.0,NaN,NaN,1.388146e+09,8.277200e+07,1.521905e+09,-222079000.0,-453034000.0,...,2555000.0,1.173000e+08,-6.28724,3.143570e+08,65805000.0,-453034000.0,1.299826e+09,150414000.0,86609000.0,2018
326388,1735828,1.161394e+09,-4489000.0,NaN,NaN,1.388146e+09,8.277200e+07,1.521905e+09,-222079000.0,-453034000.0,...,2555000.0,1.173000e+08,-6.28724,3.143570e+08,65805000.0,-453034000.0,1.299826e+09,150414000.0,86609000.0,2018
23404,1735828,1.346769e+09,4001000.0,NaN,NaN,1.574816e+09,1.126040e+08,1.764769e+09,-271687000.0,-502231000.0,...,1246000.0,1.685400e+08,-6.91830,4.363010e+08,18058000.0,-502231000.0,1.493082e+09,126938000.0,144810000.0,2019
342465,1735828,1.346769e+09,4001000.0,NaN,NaN,1.574816e+09,1.126040e+08,1.764769e+09,-271687000.0,-502231000.0,...,1246000.0,1.685400e+08,-6.91830,4.363010e+08,18058000.0,-502231000.0,1.493082e+09,126938000.0,144810000.0,2019

In [13]:
# iterate over the dictionary, and for each year concatanate 
# the corresponding five years for each company in the list
# to the final dataframe: datum.

# create an issue log
issues = ''

# create a dataframe to record the issue
df_issues = pd.DataFrame(columns=['CIK', 'Year', '#rows'])

# create an empty df with the data columns
datum = pd.DataFrame(columns=data_cl.columns)

# iterate over the dictionary
for key, value in CIK.items():
    # for each company (cik) in the list of the year (key)
    for cik in value:
        # take rows of the data for that cik code and the same year as key
        df = data_cl[(data_cl.Instrument == cik) & (data_cl.Year == key)]
        if df.shape[0] > 1:
            issues += '\n ' + str(cik) + ' for the year ' + str(key) + ' has ' + str(df.shape[0]) + ' rows.'
            new_row = {'CIK': cik, 'Year': key, '#rows': df.shape[0]}
            df_issues = df_issues.append(new_row, ignore_index=True)
        datum = pd.concat([datum, df])

print(datum.shape)
datum.head()

(21865, 23)

,Instrument,Total Debt,Accounts Payable (CF),Inventories (CF),Retained Earnings (Accumulated Deficit),Net Debt Incl. Pref.Stock & Min.Interest,Total Current Assets,Total Liabilities,Total Equity,Tangible Book Value - Banks,...,Cash and Short Term Investments,Market Value for Company,Tangible Book Value Per Share,Net Sales,Operating Income,Tangible Book Value - Utility,"Total Assets, Reported",Depreciation And Amortization,Total Current Liabilities,Year
605,1107978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000
315,909326,5066000.0,-5674000.0,5488000.0,-15217000.0,-25696000.0,92262000.0,22654000.0,101634000.0,77531000.0,...,35762000.0,890720000.0,3.34223,92948000.0,-39475000.0,77531000.0,124288000.0,1628000.0,19778000.0,2000
316,909326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000
30348,909326,5066000.0,-5674000.0,5488000.0,-15217000.0,-25696000.0,92262000.0,22654000.0,101634000.0,77531000.0,...,35762000.0,890720000.0,3.34223,92948000.0,-39475000.0,77531000.0,124288000.0,1628000.0,19778000.0,2000
30349,909326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000

In [14]:
print(issues)

 909326 for the year 2000 has 4 rows.
 944163 for the year 2000 has 2 rows.
 1122380 for the year 2000 has 2 rows.
 106640 for the year 2000 has 2 rows.
 26780 for the year 2000 has 2 rows.
 73887 for the year 2000 has 2 rows.
 100517 for the year 2000 has 2 rows.
 843964 for the year 2000 has 2 rows.
 1114365 for the year 2000 has 2 rows.
 1091862 for the year 2000 has 2 rows.
 932127 for the year 2000 has 2 rows.
 1085734 for the year 2000 has 2 rows.
 1169709 for the year 2000 has 2 rows.
 104777 for the year 2000 has 2 rows.
 1046880 for the year 2000 has 2 rows.
 868725 for the year 2000 has 4 rows.
 1110418 for the year 2000 has 2 rows.
 827809 for the year 2000 has 2 rows.
 350698 for the year 2000 has 2 rows.
 797167 for the year 2000 has 2 rows.
 1210936 for the year 2000 has 2 rows.
 811596 for the year 2000 has 2 rows.
 889423 for the year 2000 has 4 rows.
 354963 for the year 2000 has 3 rows.
 1043156 for the year 2000 has 2 rows.
 774937 for the year 2000 has 2 rows.
 885551 for the year 2000 has 2 rows.
 318259 for the year 2000 has 2 rows.
 1018693 for the year 2000 has 2 rows.
 1049442 for the year 2000 has 2 rows.
 764794 for the year 2000 has 2 rows.
 826253 for the year 2000 has 2 rows.
 21438 for the year 2000 has 4 rows.
 76791 for the year 2000 has 2 rows.
 54291 for the year 2000 has 2 rows.
 1023128 for the year 2000 has 2 rows.
 1023139 for the year 2000 has 2 rows.
 1047739 for the year 2000 has 2 rows.
 7431 for the year 2000 has 2 rows.
 757011 for the year 2000 has 2 rows.
 13610 for the year 2000 has 3 rows.
 1107280 for the year 2000 has 2 rows.
 945489 for the year 2000 has 2 rows.
 85417 for the year 2000 has 2 rows.
 818682 for the year 2000 has 2 rows.
 878079 for the year 2000 has 2 rows.
 1052163 for the year 2000 has 2 rows.
 855581 for the year 2000 has 2 rows.
 1070630 for the year 2000 has 2 rows.
 1060390 for the year 2000 has 2 rows.
 837173 for the year 2000 has 2 rows.
 1093207 for the year 2000 has 2 rows.
 859735 for the year 2000 has 2 rows.
 30302 for the year 2000 has 2 rows.
 1238631 for the year 2000 has 2 rows.
 1029738 for the year 2000 has 2 rows.
 1136294 for the year 2000 has 2 rows.
 888507 for the year 2000 has 2 rows.
 1048268 for the year 2000 has 2 rows.
 57055 for the year 2000 has 4 rows.
 1013488 for the year 2000 has 2 rows.
 1023734 for the year 2000 has 2 rows.
 18172 for the year 2000 has 2 rows.
 1029893 for the year 2000 has 2 rows.
 319240 for the year 2000 has 2 rows.
 829224 for the year 2000 has 2 rows.
 1034054 for the year 2000 has 2 rows.
 880460 for the year 2000 has 2 rows.
 30554 for the year 2000 has 3 rows.
 837472 for the year 2000 has 2 rows.
 812906 for the year 2000 has 2 rows.
 806817 for the year 2000 has 2 rows.
 1030058 for the year 2000 has 2 rows.
 1038274 for the year 2000 has 2 rows.
 839621 for the year 2000 has 2 rows.
 1001463 for the year 2000 has 2 rows.
 909326 for the year 2001 has 4 rows.
 944163 for the year 2001 has 2 rows.
 1122380 for the year 2001 has 2 rows.
 1097805 for the year 2001 has 4 rows.
 2178 for the year 2001 has 2 rows.
 1108109 for the year 2001 has 3 rows.
 106640 for the year 2001 has 2 rows.
 26780 for the year 2001 has 2 rows.
 73887 for the year 2001 has 2 rows.
 100517 for the year 2001 has 2 rows.
 843964 for the year 2001 has 2 rows.
 1009891 for the year 2001 has 2 rows.
 1114365 for the year 2001 has 2 rows.
 1091862 for the year 2001 has 2 rows.
 921878 for the year 2001 has 3 rows.
 932127 for the year 2001 has 2 rows.
 1085734 for the year 2001 has 2 rows.
 1169709 for the year 2001 has 2 rows.
 104777 for the year 2001 has 2 rows.
 94538 for the year 2001 has 2 rows.
 1046880 for the year 2001 has 2 rows.
 868725 for the year 2001 has 4 rows.
 1110418 for the year 2001 has 2 rows.
 827809 for the year 2001 has 2 rows.
 911801 for the year 2001 has 2 rows.
 1104332 for the year 2001 has 2 rows.
 1141197 for the year 2001 has 2 rows.
 940510 for the year 2001 has 2 rows.
 350698 for the year 2001 has 2 rows.
 797167 for the year 2001 has 2 rows.
 1071598 for the year 2001 has 2 rows.
 1210936 for the year 2001 has 2 rows.
 311871 for the year 2001 has 2 rows.
 901696 for the year 2001 has 2 rows.
 791115 for the year 2001 has 2 rows.
 811596 for the year 2001 has 2 rows.
 889423 for the year 2001 has 4 rows.
 6769 for the year 2001 has 2 rows.
 909950 for the year 2001 has 2 rows.
 354963 for the year 2001 has 3 rows.
 744106 for the year 2001 has 2 rows.
 1084103 for the year 2001 has 2 rows.
 1043156 for the year 2001 has 2 rows.
 19161 for the year 2001 has 2 rows.
 1172222 for the year 2001 has 2 rows.
 1133324 for the year 2001 has 2 rows.
 774937 for the year 2001 has 2 rows.
 885551 for the year 2001 has 2 rows.
 318259 for the year 2001 has 2 rows.
 1096509 for the year 2001 has 2 rows.
 1018693 for the year 2001 has 2 rows.
 1049442 for the year 2001 has 2 rows.
 912241 for the year 2001 has 2 rows.
 764794 for the year 2001 has 2 rows.
 770944 for the year 2001 has 2 rows.
 826253 for the year 2001 has 2 rows.
 818074 for the year 2001 has 2 rows.
 103341 for the year 2001 has 2 rows.
 1043382 for the year 2001 has 2 rows.
 21438 for the year 2001 has 4 rows.
 916457 for the year 2001 has 2 rows.
 76791 for the year 2001 has 2 rows.
 1092605 for the year 2001 has 2 rows.
 54291 for the year 2001 has 2 rows.
 320573 for the year 2001 has 2 rows.
 855109 for the year 2001 has 4 rows.
 1256536 for the year 2001 has 2 rows.
 1061985 for the year 2001 has 2 rows.
 1287286 for the year 2001 has 2 rows.
 1023128 for the year 2001 has 2 rows.
 1023139 for the year 2001 has 2 rows.
 722104 for the year 2001 has 2 rows.
 1047739 for the year 2001 has 2 rows.
 1156295 for the year 2001 has 2 rows.
 1045739 for the year 2001 has 4 rows.
 1058033 for the year 2001 has 2 rows.
 27904 for the year 2001 has 2 rows.
 851199 for the year 2001 has 2 rows.
 7431 for the year 2001 has 2 rows.
 757011 for the year 2001 has 2 rows.
 13610 for the year 2001 has 3 rows.
 109870 for the year 2001 has 2 rows.
 1107280 for the year 2001 has 2 rows.
 945489 for the year 2001 has 2 rows.
 85417 for the year 2001 has 2 rows.
 919013 for the year 2001 has 2 rows.
 912875 for the year 2001 has 2 rows.
 804331 for the year 2001 has 2 rows.
 1103345 for the year 2001 has 2 rows.
 818682 for the year 2001 has 2 rows.
 878079 for the year 2001 has 2 rows.
 1052163 for the year 2001 has 2 rows.
 855581 for the year 2001 has 2 rows.
 1070630 for the year 2001 has 2 rows.
 1060390 for the year 2001 has 2 rows.
 837173 for the year 2001 has 2 rows.
 935493 for the year 2001 has 2 rows.
 1171014 for the year 2001 has 2 rows.
 1093207 for the year 2001 has 2 rows.
 859735 for the year 2001 has 2 rows.
 30302 for the year 2001 has 2 rows.
 1283683 for the year 2001 has 2 rows.
 1238631 for the year 2001 has 2 rows.
 1029738 for the year 2001 has 2 rows.
 1136294 for the year 2001 has 2 rows.
 888507 for the year 2001 has 2 rows.
 847555 for the year 2001 has 2 rows.
 1048268 for the year 2001 has 2 rows.
 57055 for the year 2001 has 4 rows.
 806624 for the year 2001 has 2 rows.
 1013488 for the year 2001 has 2 rows.
 1023734 for the year 2001 has 2 rows.
 18172 for the year 2001 has 2 rows.
 1029893 for the year 2001 has 2 rows.
 319240 for the year 2001 has 2 rows.
 829224 for the year 2001 has 2 rows.
 1034054 for the year 2001 has 2 rows.
 796486 for the year 2001 has 2 rows.
 880460 for the year 2001 has 2 rows.
 30554 for the year 2001 has 3 rows.
 837472 for the year 2001 has 2 rows.
 812906 for the year 2001 has 2 rows.
 1021848 for the year 2001 has 2 rows.
 806817 for the year 2001 has 2 rows.
 1030058 for the year 2001 has 2 rows.
 1038274 for the year 2001 has 2 rows.
 839621 for the year 2001 has 2 rows.
 1001463 for the year 2001 has 2 rows.
 909326 for the year 2002 has 4 rows.
 944163 for the year 2002 has 2 rows.
 919583 for the year 2002 has 2 rows.
 1124394 for the year 2002 has 2 rows.
 1122380 for the year 2002 has 2 rows.
 1097805 for the year 2002 has 4 rows.
 2178 for the year 2002 has 2 rows.
 1108109 for the year 2002 has 3 rows.
 106640 for the year 2002 has 2 rows.
 26780 for the year 2002 has 2 rows.
 73887 for the year 2002 has 2 rows.
 100517 for the year 2002 has 2 rows.
 1372326 for the year 2002 has 2 rows.
 843964 for the year 2002 has 2 rows.
 1009891 for the year 2002 has 2 rows.
 1089775 for the year 2002 has 2 rows.
 1132784 for the year 2002 has 2 rows.
 1114365 for the year 2002 has 2 rows.
 1091862 for the year 2002 has 2 rows.
 921878 for the year 2002 has 3 rows.
 12570 for the year 2002 has 2 rows.
 932127 for the year 2002 has 2 rows.
 1085734 for the year 2002 has 2 rows.
 1169709 for the year 2002 has 2 rows.
 104777 for the year 2002 has 2 rows.
 94538 for the year 2002 has 2 rows.
 1046880 for the year 2002 has 2 rows.
 868725 for the year 2002 has 4 rows.
 1051009 for the year 2002 has 2 rows.
 1110418 for the year 2002 has 2 rows.
 827809 for the year 2002 has 2 rows.
 911801 for the year 2002 has 2 rows.
 1292731 for the year 2002 has 2 rows.
 1104332 for the year 2002 has 2 rows.
 1141197 for the year 2002 has 2 rows.
 1092050 for the year 2002 has 2 rows.
 940510 for the year 2002 has 2 rows.
 350698 for the year 2002 has 2 rows.
 797167 for the year 2002 has 2 rows.
 1071598 for the year 2002 has 2 rows.
 788983 for the year 2002 has 2 rows.
 1210936 for the year 2002 has 2 rows.
 311871 for the year 2002 has 2 rows.
 901696 for the year 2002 has 2 rows.
 791115 for the year 2002 has 2 rows.
 811596 for the year 2002 has 2 rows.
 889423 for the year 2002 has 4 rows.
 1043055 for the year 2002 has 2 rows.
 6769 for the year 2002 has 2 rows.
 1049210 for the year 2002 has 2 rows.
 909950 for the year 2002 has 2 rows.
 887433 for the year 2002 has 4 rows.
 354963 for the year 2002 has 3 rows.
 744106 for the year 2002 has 2 rows.
 811696 for the year 2002 has 2 rows.
 1084103 for the year 2002 has 2 rows.
 1043156 for the year 2002 has 2 rows.
 19161 for the year 2002 has 2 rows.
 912093 for the year 2002 has 2 rows.
 1082084 for the year 2002 has 2 rows.
 885475 for the year 2002 has 6 rows.
 1172222 for the year 2002 has 2 rows.
 1020676 for the year 2002 has 2 rows.
 1133324 for the year 2002 has 2 rows.
 774937 for the year 2002 has 2 rows.
 1207070 for the year 2002 has 2 rows.
 885551 for the year 2002 has 2 rows.
 318259 for the year 2002 has 2 rows.
 1096509 for the year 2002 has 2 rows.
 881468 for the year 2002 has 2 rows.
 1018693 for the year 2002 has 2 rows.
 1018710 for the year 2002 has 2 rows.
 1049442 for the year 2002 has 2 rows.
 834408 for the year 2002 has 2 rows.
 912241 for the year 2002 has 2 rows.
 764794 for the year 2002 has 2 rows.
 1051512 for the year 2002 has 2 rows.
 770944 for the year 2002 has 2 rows.
 1125259 for the year 2002 has 2 rows.
 826253 for the year 2002 has 2 rows.
 818074 for the year 2002 has 2 rows.
 103341 for the year 2002 has 2 rows.
 1043382 for the year 2002 has 2 rows.
 21438 for the year 2002 has 4 rows.
 916457 for the year 2002 has 2 rows.
 76791 for the year 2002 has 2 rows.
 1092605 for the year 2002 has 2 rows.
 1303565 for the year 2002 has 4 rows.
 54291 for the year 2002 has 2 rows.
 1311803 for the year 2002 has 2 rows.
 320573 for the year 2002 has 2 rows.
 855109 for the year 2002 has 4 rows.
 1236038 for the year 2002 has 2 rows.
 1256536 for the year 2002 has 2 rows.
 1178717 for the year 2002 has 2 rows.
 1061985 for the year 2002 has 2 rows.
 906337 for the year 2002 has 2 rows.
 1137778 for the year 2002 has 2 rows.
 1287286 for the year 2002 has 2 rows.
 1023128 for the year 2002 has 2 rows.
 935063 for the year 2002 has 2 rows.
 81050 for the year 2002 has 2 rows.
 1023139 for the year 2002 has 2 rows.
 1100981 for the year 2002 has 2 rows.
 722104 for the year 2002 has 2 rows.
 1047739 for the year 2002 has 2 rows.
 1178818 for the year 2002 has 2 rows.
 1156295 for the year 2002 has 2 rows.
 1311953 for the year 2002 has 2 rows.
 1045739 for the year 2002 has 4 rows.
 1058033 for the year 2002 has 2 rows.
 27904 for the year 2002 has 2 rows.
 851199 for the year 2002 has 2 rows.
 7431 for the year 2002 has 2 rows.
 720145 for the year 2002 has 2 rows.
 757011 for the year 2002 has 2 rows.
 13610 for the year 2002 has 3 rows.
 109870 for the year 2002 has 2 rows.
 703799 for the year 2002 has 2 rows.
 1107280 for the year 2002 has 2 rows.
 945489 for the year 2002 has 2 rows.
 1051985 for the year 2002 has 2 rows.
 1232229 for the year 2002 has 2 rows.
 1023362 for the year 2002 has 2 rows.
 742814 for the year 2002 has 2 rows.
 85417 for the year 2002 has 2 rows.
 822746 for the year 2002 has 2 rows.
 1392091 for the year 2002 has 2 rows.
 919013 for the year 2002 has 2 rows.
 912875 for the year 2002 has 2 rows.
 804331 for the year 2002 has 2 rows.
 1103345 for the year 2002 has 2 rows.
 726513 for the year 2002 has 2 rows.
 818682 for the year 2002 has 2 rows.
 878079 for the year 2002 has 2 rows.
 1052163 for the year 2002 has 2 rows.
 855581 for the year 2002 has 2 rows.
 1351197 for the year 2002 has 2 rows.
 1070630 for the year 2002 has 2 rows.
 1060390 for the year 2002 has 2 rows.
 1181232 for the year 2002 has 2 rows.
 1035826 for the year 2002 has 2 rows.
 837173 for the year 2002 has 2 rows.
 935493 for the year 2002 has 2 rows.
 1171014 for the year 2002 has 2 rows.
 1093207 for the year 2002 has 2 rows.
 859735 for the year 2002 has 2 rows.
 30302 for the year 2002 has 2 rows.
 1283683 for the year 2002 has 2 rows.
 859747 for the year 2002 has 2 rows.
 1238631 for the year 2002 has 2 rows.
 1029738 for the year 2002 has 2 rows.
 949876 for the year 2002 has 2 rows.
 1136294 for the year 2002 has 2 rows.
 351917 for the year 2002 has 2 rows.
 802481 for the year 2002 has 2 rows.
 888507 for the year 2002 has 2 rows.
 847555 for the year 2002 has 2 rows.
 1048268 for the year 2002 has 2 rows.
 57055 for the year 2002 has 4 rows.
 806624 for the year 2002 has 2 rows.
 843494 for the year 2002 has 2 rows.
 1013488 for the year 2002 has 2 rows.
 1023734 for the year 2002 has 2 rows.
 18172 for the year 2002 has 2 rows.
 1083132 for the year 2002 has 2 rows.
 1029893 for the year 2002 has 2 rows.
 319240 for the year 2002 has 2 rows.
 829224 for the year 2002 has 2 rows.
 1034054 for the year 2002 has 2 rows.
 796486 for the year 2002 has 2 rows.
 776008 for the year 2002 has 2 rows.
 880460 for the year 2002 has 2 rows.
 30554 for the year 2002 has 3 rows.
 837472 for the year 2002 has 2 rows.
 812906 for the year 2002 has 2 rows.
 1101680 for the year 2002 has 2 rows.
 1351548 for the year 2002 has 2 rows.
 1103764 for the year 2002 has 2 rows.
 1021848 for the year 2002 has 2 rows.
 806817 for the year 2002 has 2 rows.
 1327012 for the year 2002 has 2 rows.
 1030058 for the year 2002 has 2 rows.
 1261482 for the year 2002 has 2 rows.
 1038274 for the year 2002 has 2 rows.
 839621 for the year 2002 has 2 rows.
 884719 for the year 2002 has 4 rows.
 1001463 for the year 2002 has 2 rows.
 909326 for the year 2003 has 4 rows.
 22551 for the year 2003 has 2 rows.
 716823 for the year 2003 has 2 rows.
 40987 for the year 2003 has 2 rows.
 944163 for the year 2003 has 2 rows.
 919583 for the year 2003 has 2 rows.
 317477 for the year 2003 has 2 rows.
 1124394 for the year 2003 has 2 rows.
 829499 for the year 2003 has 2 rows.
 1122380 for the year 2003 has 2 rows.
 1097805 for the year 2003 has 4 rows.
 1216596 for the year 2003 has 2 rows.
 1091667 for the year 2003 has 4 rows.
 1081158 for the year 2003 has 2 rows.
 899166 for the year 2003 has 4 rows.
 946283 for the year 2003 has 2 rows.
 1013871 for the year 2003 has 2 rows.
 2178 for the year 2003 has 2 rows.
 878731 for the year 2003 has 2 rows.
 1108109 for the year 2003 has 3 rows.
 106640 for the year 2003 has 2 rows.
 26780 for the year 2003 has 2 rows.
 854171 for the year 2003 has 2 rows.
 73887 for the year 2003 has 2 rows.
 1071265 for the year 2003 has 2 rows.
 100517 for the year 2003 has 2 rows.
 1372326 for the year 2003 has 2 rows.
 1138862 for the year 2003 has 2 rows.
 909494 for the year 2003 has 2 rows.
 843964 for the year 2003 has 2 rows.
 1030339 for the year 2003 has 2 rows.
 1667280 for the year 2003 has 2 rows.
 1009891 for the year 2003 has 2 rows.
 1038572 for the year 2003 has 2 rows.
 1089775 for the year 2003 has 2 rows.
 1132784 for the year 2003 has 2 rows.
 1018099 for the year 2003 has 2 rows.
 943605 for the year 2003 has 2 rows.
 1114365 for the year 2003 has 2 rows.
 1091862 for the year 2003 has 2 rows.
 921878 for the year 2003 has 3 rows.
 12570 for the year 2003 has 2 rows.
 932127 for the year 2003 has 2 rows.
 821536 for the year 2003 has 2 rows.
 737572 for the year 2003 has 2 rows.
 1104161 for the year 2003 has 2 rows.
 1085734 for the year 2003 has 2 rows.
 1169709 for the year 2003 has 2 rows.
 104777 for the year 2003 has 2 rows.
 94538 for the year 2003 has 2 rows.
 786765 for the year 2003 has 2 rows.
 1046880 for the year 2003 has 2 rows.
 819551 for the year 2003 has 2 rows.
 1352045 for the year 2003 has 2 rows.
 1171825 for the year 2003 has 4 rows.
 868725 for the year 2003 has 4 rows.
 1051009 for the year 2003 has 2 rows.
 1110418 for the year 2003 has 2 rows.
 815508 for the year 2003 has 2 rows.
 827809 for the year 2003 has 2 rows.
 1173924 for the year 2003 has 2 rows.
 1393066 for the year 2003 has 2 rows.
 723371 for the year 2003 has 2 rows.
 842162 for the year 2003 has 2 rows.
 911801 for the year 2003 has 2 rows.
 1292731 for the year 2003 has 2 rows.
 805305 for the year 2003 has 4 rows.
 858558 for the year 2003 has 2 rows.
 1104332 for the year 2003 has 2 rows.
 1141197 for the year 2003 has 2 rows.
 1092050 for the year 2003 has 2 rows.
 940510 for the year 2003 has 2 rows.
 356830 for the year 2003 has 2 rows.
 350698 for the year 2003 has 2 rows.
 797167 for the year 2003 has 2 rows.
 1071598 for the year 2003 has 2 rows.
 788983 for the year 2003 has 2 rows.
 1167880 for the year 2003 has 4 rows.
 840216 for the year 2003 has 2 rows.
 1210936 for the year 2003 has 2 rows.
 311871 for the year 2003 has 2 rows.
 901696 for the year 2003 has 2 rows.
 899647 for the year 2003 has 2 rows.
 840256 for the year 2003 has 2 rows.
 791115 for the year 2003 has 2 rows.
 811596 for the year 2003 has 2 rows.
 889423 for the year 2003 has 4 rows.
 852570 for the year 2003 has 2 rows.
 944739 for the year 2003 has 2 rows.
 948844 for the year 2003 has 2 rows.
 1043055 for the year 2003 has 2 rows.
 891504 for the year 2003 has 2 rows.
 6769 for the year 2003 has 2 rows.
 1110647 for the year 2003 has 2 rows.
 1372791 for the year 2003 has 2 rows.
 750199 for the year 2003 has 2 rows.
 1049210 for the year 2003 has 2 rows.
 909950 for the year 2003 has 2 rows.
 1176193 for the year 2003 has 2 rows.
 887433 for the year 2003 has 4 rows.
 354963 for the year 2003 has 3 rows.
 1096339 for the year 2003 has 2 rows.
 1088162 for the year 2003 has 2 rows.
 744106 for the year 2003 has 2 rows.
 1311396 for the year 2003 has 2 rows.
 811696 for the year 2003 has 2 rows.
 854709 for the year 2003 has 2 rows.
 1362614 for the year 2003 has 2 rows.
 1084103 for the year 2003 has 2 rows.
 101063 for the year 2003 has 2 rows.
 1061580 for the year 2003 has 2 rows.
 1102542 for the year 2003 has 2 rows.
 1043156 for the year 2003 has 2 rows.
 19161 for the year 2003 has 2 rows.
 912093 for the year 2003 has 2 rows.
 1080029 for the year 2003 has 2 rows.
 1082084 for the year 2003 has 2 rows.
 885475 for the year 2003 has 6 rows.
 357097 for the year 2003 has 2 rows.
 1288946 for the year 2003 has 2 rows.
 1172222 for the year 2003 has 2 rows.
 1020676 for the year 2003 has 2 rows.
 1145202 for the year 2003 has 2 rows.
 1133324 for the year 2003 has 2 rows.
 1202963 for the year 2003 has 2 rows.
 713492 for the year 2003 has 2 rows.
 64279 for the year 2003 has 2 rows.
 774937 for the year 2003 has 2 rows.
 1207070 for the year 2003 has 2 rows.
 4904 for the year 2003 has 2 rows.

In [15]:
print(df_issues.shape)
df_issues.sort_values(by=['#rows'], ascending=False, inplace=True)
df_issues.head()

(4615, 3)

          CIK  Year #rows
3550  1047919  2012     6
1080  1310094  2004     6
2694  1047919  2009     6
759    885475  2004     6
1249   885475  2005     6

In [16]:
# drop the duplicate rows
datum.drop_duplicates(inplace=True)

print(datum.shape)

datum.sort_values(by=['Instrument', 'Year'])

(17556, 23)

,Instrument,Total Debt,Accounts Payable (CF),Inventories (CF),Retained Earnings (Accumulated Deficit),Net Debt Incl. Pref.Stock & Min.Interest,Total Current Assets,Total Liabilities,Total Equity,Tangible Book Value - Banks,...,Cash and Short Term Investments,Market Value for Company,Tangible Book Value Per Share,Net Sales,Operating Income,Tangible Book Value - Utility,"Total Assets, Reported",Depreciation And Amortization,Total Current Liabilities,Year
72431,1750,2.602240e+08,-25261000.0,-31749000.0,156479000.0,2.257020e+08,4.366560e+08,3.999640e+08,310235000.0,264329000.0,...,34522000.0,1.640000e+08,8.29398,6.387210e+08,-81289000.0,264329000.0,7.101990e+08,NaN,150464000.0,2003
88508,1750,2.569140e+08,-2841000.0,17755000.0,143272000.0,2.277600e+08,3.964120e+08,3.916330e+08,294988000.0,249037000.0,...,29154000.0,4.790900e+08,7.81881,5.998420e+08,908000.0,249037000.0,6.866210e+08,NaN,203575000.0,2004
104585,1750,2.520580e+08,6642000.0,15602000.0,146776000.0,2.183610e+08,4.322040e+08,4.076080e+08,301684000.0,257263000.0,...,33697000.0,4.389800e+08,7.97838,6.444690e+08,20281000.0,257263000.0,7.092920e+08,NaN,131261000.0,2005
120662,1750,2.309040e+08,19244000.0,-12013000.0,162229000.0,1.903960e+08,4.745420e+08,4.174860e+08,314744000.0,270328000.0,...,40508000.0,8.022800e+08,8.29583,7.404270e+08,38479000.0,270328000.0,7.322300e+08,NaN,160025000.0,2006
136739,1750,3.208650e+08,19735000.0,-58297000.0,197392000.0,1.991270e+08,6.244540e+08,5.561020e+08,422717000.0,378285000.0,...,121738000.0,1.079330e+09,10.32043,8.855180e+08,61279000.0,378285000.0,9.788190e+08,NaN,187788000.0,2007
3838,2034,7.608000e+06,4174000.0,694000.0,40863000.0,-7.967000e+06,1.007240e+08,4.241300e+07,73290000.0,63469000.0,...,15575000.0,1.042400e+08,2.87098,2.293290e+08,7336000.0,63469000.0,1.157030e+08,NaN,42413000.0,2003
5048,2034,3.286000e+06,2907000.0,-4597000.0,46142000.0,-1.785400e+07,1.101150e+08,3.895000e+07,84569000.0,76374000.0,...,21140000.0,2.651600e+08,3.27138,2.699610e+08,13027000.0,76374000.0,1.235190e+08,NaN,38950000.0,2004
6258,2034,1.000000e+06,9563000.0,2166000.0,56490000.0,-3.206100e+07,1.329740e+08,4.943100e+07,100266000.0,93386000.0,...,33218000.0,3.023400e+08,3.87205,2.963590e+08,16118000.0,93386000.0,1.496970e+08,NaN,46554000.0,2005
7468,2034,6.260000e+05,-8681000.0,-10188000.0,62864000.0,-2.422100e+07,1.316400e+08,4.137300e+07,107655000.0,102782000.0,...,25018000.0,1.598900e+08,4.23285,3.134310e+08,11590000.0,102782000.0,1.490280e+08,NaN,37391000.0,2006
8678,2034,5.000000e+05,-3962000.0,4909000.0,68464000.0,-3.630900e+07,1.411060e+08,5.153900e+07,115053000.0,109509000.0,...,37041000.0,2.098400e+08,4.51063,2.973280e+08,12429000.0,109509000.0,1.665920e+08,NaN,36399000.0,2007
15938,2034,4.576500e+07,-978000.0,-9926000.0,102344000.0,1.938500e+07,1.919690e+08,1.312770e+08,168003000.0,89257000.0,...,26380000.0,2.743300e+08,3.31355,4.443880e+08,25366000.0,89257000.0,2.992800e+08,NaN,73641000.0,2013
17148,2034,3.206900e+07,-3228000.0,1632000.0,118615000.0,-3.306000e+06,2.183000e+08,1.287900e+08,194640000.0,120283000.0,...,35375000.0,7.036700e+08,4.32191,4.996900e+08,34416000.0,120283000.0,3.234300e+08,NaN,89907000.0,2014
18358,2034,1.055010e+08,5216000.0,-7764000.0,140768000.0,6.185800e+07,2.763540e+08,2.344000e+08,233584000.0,79113000.0,...,43643000.0,6.307100e+08,2.74965,5.101790e+08,44272000.0,79113000.0,4.679840e+08,NaN,118523000.0,2015
19568,2034,1.101570e+08,8133000.0,-229000.0,167208000.0,7.272100e+07,3.103100e+08,2.355630e+08,254211000.0,107344000.0,...,37436000.0,7.959600e+08,3.68285,5.469510e+08,56333000.0,107344000.0,4.897740e+08,4790000.0,125000000.0,2016
20778,2034,1.187890e+08,-8937000.0,-2489000.0,194804000.0,5.108000e+07,3.526610e+08,2.363360e+08,304442000.0,157500000.0,...,67709000.0,6.602300e+08,5.32184,5.585240e+08,58028000.0,157500000.0,5.407780e+08,NaN,98906000.0,2017
1349,2178,9.900000e+06,158037000.0,-13187000.0,23906000.0,-1.423700e+07,2.642250e+08,2.570270e+08,36021000.0,36021000.0,...,24137000.0,5.905000e+07,8.54064,3.995477e+09,7963000.0,36021000.0,2.930480e+08,6071000.0,244787000.0,2001
2559,2178,1.190000e+07,109022000.0,-13978000.0,32198000.0,-2.424000e+07,4.200320e+08,4.037310e+08,44313000.0,44313000.0,...,36140000.0,3.290000e+07,10.50669,7.022160e+09,12861000.0,44313000.0,4.480440e+08,6745000.0,387376000.0,2002
3769,2178,1.247500e+07,-193875000.0,25763000.0,27081000.0,-1.702000e+06,1.993050e+08,1.878310e+08,39196000.0,39196000.0,...,14177000.0,2.214000e+07,9.29344,3.483310e+09,-14265000.0,39196000.0,2.270270e+08,6726000.0,168971000.0,2003
4979,2178,1.147500e+07,-14356000.0,3534000.0,27985000.0,-1.578700e+07,1.794000e+08,1.620200e+08,40100000.0,40100000.0,...,27262000.0,5.715000e+07,9.50778,1.767350e+09,5122000.0,40100000.0,2.021200e+08,5565000.0,148084000.0,2004
6189,2178,1.147500e+07,7947000.0,-1319000.0,30117000.0,-1.686700e+07,1.854230e+08,1.683750e+08,42232000.0,42232000.0,...,28342000.0,7.466000e+07,10.01328,1.720928e+09,9101000.0,42232000.0,2.106070e+08,5164000.0,152665000.0,2005
7399,2178,1.147500e+07,15138000.0,-5072000.0,37460000.0,-8.467000e+06,2.093390e+08,1.892790e+08,49575000.0,49575000.0,...,19942000.0,9.634000e+07,11.75432,2.069087e+09,13779000.0,49575000.0,2.388540e+08,6285000.0,173550000.0,2006
8609,2178,1.147500e+07,53200000.0,-320000.0,53541000.0,-7.342000e+06,2.704500e+08,2.470060e+08,65656000.0,65656000.0,...,18817000.0,1.270000e+08,15.56715,2.364833e+09,25292000.0,65656000.0,3.126620e+08,7060000.0,231129000.0,2007
9819,2178,3.000000e+06,-27682000.0,3742000.0,62253000.0,-1.766800e+07,2.417900e+08,2.149190e+08,74368000.0,74368000.0,...,20668000.0,1.084000e+08,17.63278,2.246603e+09,14967000.0,74368000.0,2.892870e+08,9485000.0,206582000.0,2008
11029,2178,0.000000e+00,66556000.0,-6826000.0,77327000.0,-2.369700e+07,3.118930e+08,2.676330e+08,89442000.0,89442000.0,...,23697000.0,7.171000e+07,21.20685,2.636222e+09,23907000.0,89442000.0,3.570750e+08,11384000.0,261321000.0,2009
12239,2178,0.000000e+00,-137548000.0,569000.0,69646000.0,-1.820800e+07,1.693660e+08,1.291650e+08,81761000.0,81761000.0,...,18208000.0,9.301000e+07,19.38567,4.159672e+09,-11474000.0,81761000.0,2.109260e+08,13373000.0,127807000.0,2010
13449,2178,0.000000e+00,43069000.0,-1053000.0,71686000.0,-1.680600e+07,2.025630e+08,1.656000e+08,83801000.0,83801000.0,...,16806000.0,1.032900e+08,19.86936,1.943128e+09,6401000.0,83801000.0,2.494010e+08,10320000.0,164191000.0,2011
14659,2178,0.000000e+00,40521000.0,669000.0,78040000.0,-2.903200e+07,2.469760e+08,2.111500e+08,90155000.0,90155000.0,...,29032000.0,1.227800e+08,21.37590,2.083781e+09,12425000.0,90155000.0,3.013050e+08,11314000.0,206998000.0,2012
15869,2178,0.000000e+00,47662000.0,-5598000.0,98567000.0,-3.706600e+07,3.049650e+08,2.681580e+08,110682000.0,110682000.0,...,37066000.0,1.479100e+08,26.24289,3.038737e+09,35206000.0,110682000.0,3.788400e+08,15885000.0,256094000.0,2013
17079,2178,0.000000e+00,10474000.0,-9579000.0,123743000.0,-4.723900e+07,3.245560e+08,2.836430e+08,135858000.0,135858000.0,...,47239000.0,2.889100e+08,32.21216,3.376085e+09,43956000.0,135858000.0,4.195010e+08,20714000.0,266082000.0,2014
18289,2178,0.000000e+00,7809000.0,606000.0,142570000.0,-7.443800e+07,3.517300e+08,2.933970e+08,154685000.0,154685000.0,...,74438000.0,2.106700e+08,36.67607,3.945969e+09,34376000.0,154685000.0,4.480820e+08,22275000.0,272169000.0,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129471,1678531,8.791000e+07,1062000.0,-127000.0,127611000.0,1.126280e+08,7.331800e+07,1.710060e+08,254149000.0,-11827000.0,...,14992000.0,NaN,-0.40200,3.266790e+08,125000000.0,-11827000.0,4.251550e+08,12790000.0,17016000.0,2006
145548,1678531,1.082620e+08,1923000.0,-438000.0,162762000.0,1.350370e+08,8.767200e+07,2.331980e+08,294618000.0,-50652000.0,...,20496000.0,NaN,-1.70611,3.784510e+08,139165000.0,-50652000.0,5.278160e+08,14940000.0,26600000.0,2007
16053,1690769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
17263,1690769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
18473,1690769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
19683,1690769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016
20893,1690769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
149562,1694426,2.687550e+08,88100000.0,11100000.0,78749000.0,1.796010e+08,2.518210e+08,4.862900e+08,119870000.0,55610000.0,...,89154000.0,8.340900e+08,1.41178,1.931900e+09,116700000.0,55610000.0,6.061600e+08,15100000.0,175814000.0,2007
165639,1694426,2.866000e+08,37100000.0,-37200000.0,169800000.0,1.118000e+08,4.106000e+08,5.672000e+08,382200000.0,289300000.0,...,174800000.0,1.085680e+09,5.65703,3.115400e+09,152800000.0,289300000.0,9.494000e+08,21800000.0,230900000.0,2008
181716,1694426,3.552000e+08,84700000.0,-19700000.0,237600000.0,2.058000e+08,4.753000e+08,7.318000e+08,512500000.0,415200000.0,...,149400000.0,2.839700e+08,7.73666,3.994200e+09,155000000.0,415200000.0,1.244300e+09,32100000.0,305000000.0,2009
197793,1694426,2.860000e+08,-193200000.0,58900000.0,256100000.0,2.707000e+08,1.940000e+08,4.834000e+08,533800000.0,444600000.0,...,15300000.0,3.657000e+08,8.28209,4.723700e+09,73700000.0,444600000.0,1.017200e+09,41300000.0,186200000.0,2010
213870,1694426,3.171000e+08,137200000.0,-46900000.0,248700000.0,2.487000e+08,3.116000e+08,6.920000e+08,531000000.0,450100000.0,...,68400000.0,4.020400e+08,8.38166,2.666700e+09,31400000.0,450100000.0,1.223000e+09,52400000.0,322200000.0,2011
229947,1694426,2.958000e+08,38900000.0,20900000.0,155300000.0,2.467000e+08,2.994000e+08,7.013000e+08,443300000.0,363500000.0,...,49100000.0,6.619700e+08,6.68159,3.755600e+09,-50800000.0,363500000.0,1.144600e+09,61100000.0,292500000.0,2012
246024,1694426,4.326000e+08,65300000.0,-166900000.0,294100000.0,2.069000e+08,1.050600e+09,1.577200e+09,653400000.0,566200000.0,...,225900000.0,1.509570e+09,9.75594,7.198200e+09,299000000.0,566200000.0,2.230600e+09,74100000.0,994700000.0,2013
262101,1694426,3.622000e+08,38900000.0,46000000.0,531400000.0,-6.080000e+07,1.359700e+09,1.724400e+09,899300000.0,809900000.0,...,601700000.0,2.069480e+09,13.58447,8.726700e+09,473100000.0,809900000.0,2.623700e+09,82500000.0,999100000.0,2014
16006,1720201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
17216,1720201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
18426,1720201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
19636,1720201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016
20846,1720201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
73718,1733998,5.266680e+08,-40000000.0,-2454000.0,147950000.0,5.502280e+08,2.103340e+08,9.328610e+08,502161000.0,468161000.0,...,10440000.0,6.892700e+08,18.55715,NaN,110211000.0,468161000.0,1.435022e+09,49640000.0,273582000.0,2003
89795,1733998,5.357470e+08,3738000.0,-8693000.0,157136000.0,5.366690e+08,1.932970e+08,9.766350e+08,490642000.0,482392000.0,...,7328000.0,7.951600e+08,18.85352,NaN,116258000.0,482392000.0,1.467277e+09,52090000.0,205007000.0,2004
105872,1733998,5.855190e+08,11593000.0,7171000.0,170053000.0,5.808130e+08,1.958340e+08,1.079063e+09,506316000.0,506316000.0,...,4706000.0,9.126400e+08,19.52024,NaN,102272000.0,506316000.0,1.585379e+09,54249000.0,214421000.0,2005
121949,1733998,6.015270e+08,16449000.0,-15618000.0,183932000.0,5.962790e+08,2.371170e+08,1.163678e+09,568517000.0,568517000.0,...,5248000.0,9.416600e+08,20.63828,NaN,110026000.0,568517000.0,1.732195e+09,57371000.0,267285000.0,2006
138026,1733998,6.562000e+08,32809000.0,-19684000.0,205687000.0,6.490570e+08,4.913480e+08,1.455373e+09,586931000.0,586931000.0,...,7143000.0,1.167310e+09,21.28158,NaN,126947000.0,586931000.0,2.042304e+09,61645000.0,479305000.0,2007
16144,1735828,3.370000e+08,2655000.0,NaN,NaN,3.339200e+08,5.978500e+07,5.551530e+08,488335000.0,484281000.0,...,3151000.0,1.351820e+09,10.13105,3.368850e+08,84495000.0,484281000.0,1.043488e+09,88178000.0,97450000.0,2013
17354,1735828,7.758380e+08,-1464000.0,NaN,NaN,7.724260e+08,8.791000e+07,1.019719e+09,670280000.0,666697000.0,...,3509000.0,1.619580e+09,11.68845,3.464600e+08,51491000.0,666697000.0,1.689999e+09,102144000.0,103723000.0,2014
18564,1735828,8.786930e+08,4194000.0,NaN,NaN,8.761830e+08,7.469900e+07,1.149437e+09,510396000.0,507330000.0,...,2584000.0,7.905600e+08,8.85701,4.854890e+08,27644000.0,507330000.0,1.659833e+09,158415000.0,93890000.0,2015
19774,1735828,9.388760e+08,-3228000.0,NaN,NaN,1.167657e+09,1.922540e+08,1.261401e+09,637205000.0,405191000.0,...,725000.0,1.216300e+08,5.87994,5.322990e+08,-356937000.0,405191000.0,1.898606e+09,173686000.0,97576000.0,2016
20984,1735828,1.427614e+09,10794000.0,NaN,NaN,1.654928e+09,1.294590e+08,1.792797e+09,-179677000.0,-411061000.0,...,2006000.0,1.538000e+08,-5.96173,3.387790e+08,-725697000.0,-411061000.0,1.613120e+09,177258000.0,81093000.0,2017

In [17]:
datum['dummy'] = 1
dummy = datum[['Instrument', 'Year', 'dummy']]

dummy.head()

      Instrument  Year  dummy
605      1107978  2000      1
315       909326  2000      1
316       909326  2000      1
26747    1038357  2000      1
29450     890908  2000      1

In [18]:
dummy = dummy.groupby(['Instrument', 'Year']).sum().reset_index()
dummy

       Instrument  Year  dummy
0            1750  2003      1
1            1750  2004      1
2            1750  2005      1
3            1750  2006      1
4            1750  2007      1
5            2034  2003      1
6            2034  2004      1
7            2034  2005      1
8            2034  2006      1
9            2034  2007      1
10           2034  2013      1
11           2034  2014      1
12           2034  2015      1
13           2034  2016      1
14           2034  2017      1
15           2178  2001      1
16           2178  2002      1
17           2178  2003      1
18           2178  2004      1
19           2178  2005      1
20           2178  2006      1
21           2178  2007      1
22           2178  2008      1
23           2178  2009      1
24           2178  2010      1
25           2178  2011      1
26           2178  2012      1
27           2178  2013      1
28           2178  2014      1
29           2178  2015      1
...           ...   ...    ...
16415     1678531  2006      1
16416     1678531  2007      1
16417     1690769  2013      1
16418     1690769  2014      1
16419     1690769  2015      1
16420     1690769  2016      1
16421     1690769  2017      1
16422     1694426  2007      1
16423     1694426  2008      1
16424     1694426  2009      1
16425     1694426  2010      1
16426     1694426  2011      1
16427     1694426  2012      1
16428     1694426  2013      1
16429     1694426  2014      1
16430     1720201  2013      1
16431     1720201  2014      1
16432     1720201  2015      1
16433     1720201  2016      1
16434     1720201  2017      1
16435     1733998  2003      1
16436     1733998  2004      1
16437     1733998  2005      1
16438     1733998  2006      1
16439     1733998  2007      1
16440     1735828  2013      1
16441     1735828  2014      1
16442     1735828  2015      1
16443     1735828  2016      1
16444     1735828  2017      1

[16445 rows x 3 columns]

In [19]:
dummy_list = dummy.dummy.to_list()
for i in range(10):
    print('Do we have', i, 'repititive rows in the list?', (i in dummy_list))

Do we have 0 repititive rows in the list? False
Do we have 1 repititive rows in the list? True
Do we have 2 repititive rows in the list? True
Do we have 3 repititive rows in the list? False
Do we have 4 repititive rows in the list? False
Do we have 5 repititive rows in the list? False
Do we have 6 repititive rows in the list? False
Do we have 7 repititive rows in the list? False
Do we have 8 repititive rows in the list? False
Do we have 9 repititive rows in the list? False

In [20]:
# how many double rows are still in the datafram?
dummy_list.count(2)

1111

In [21]:
dup_rows = dummy[dummy.dummy == 2]
dup_rows.head()

     Instrument  Year  dummy
130        4904  2003      2
131        4904  2004      2
132        4904  2005      2
133        4904  2006      2
134        4904  2007      2

In [22]:
datum.drop(columns=['dummy'], inplace=True)
datum.head()

,Instrument,Total Debt,Accounts Payable (CF),Inventories (CF),Retained Earnings (Accumulated Deficit),Net Debt Incl. Pref.Stock & Min.Interest,Total Current Assets,Total Liabilities,Total Equity,Tangible Book Value - Banks,...,Cash and Short Term Investments,Market Value for Company,Tangible Book Value Per Share,Net Sales,Operating Income,Tangible Book Value - Utility,"Total Assets, Reported",Depreciation And Amortization,Total Current Liabilities,Year
605,1107978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000
315,909326,5.066000e+06,-5674000.0,5488000.0,-1.521700e+07,-2.569600e+07,92262000.0,2.265400e+07,101634000.0,77531000.0,...,35762000.0,890720000.0,3.34223,92948000.0,-39475000.0,77531000.0,1.242880e+08,1628000.0,19778000.0,2000
316,909326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000
26747,1038357,2.175265e+09,-29800000.0,2714000.0,-1.552442e+09,2.116044e+09,201988000.0,2.692237e+09,789077000.0,789077000.0,...,59221000.0,846330000.0,7.86746,721944000.0,-566096000.0,789077000.0,3.481314e+09,337308000.0,526832000.0,2000
29450,890908,1.204000e+06,644000.0,-2000.0,5.538000e+06,1.539000e+06,5709000.0,7.148000e+06,8365000.0,8365000.0,...,1164000.0,60070000.0,0.64632,16212000.0,3927000.0,8365000.0,1.551300e+07,566000.0,4720000.0,2000

In [23]:
for ind in dup_rows.index:
    temp = datum[(datum.Instrument == dup_rows.loc[ind].Instrument) & (datum.Year == dup_rows.loc[ind].Year)]
    temp = temp.notnull().astype('int')
    temp['noNANs'] = temp.sum(axis=1)
    inds = list(temp.index)
    if temp.loc[inds[0]].noNANs > temp.loc[inds[1]].noNANs:
        datum.drop(index=inds[1], inplace=True)
    else:
        datum.drop(index=inds[0], inplace=True)

print(datum.shape)
datum.head()

(16445, 23)

,Instrument,Total Debt,Accounts Payable (CF),Inventories (CF),Retained Earnings (Accumulated Deficit),Net Debt Incl. Pref.Stock & Min.Interest,Total Current Assets,Total Liabilities,Total Equity,Tangible Book Value - Banks,...,Cash and Short Term Investments,Market Value for Company,Tangible Book Value Per Share,Net Sales,Operating Income,Tangible Book Value - Utility,"Total Assets, Reported",Depreciation And Amortization,Total Current Liabilities,Year
605,1107978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000
315,909326,5.066000e+06,-5674000.0,5488000.0,-1.521700e+07,-2.569600e+07,92262000.0,2.265400e+07,101634000.0,77531000.0,...,35762000.0,890720000.0,3.34223,92948000.0,-39475000.0,77531000.0,1.242880e+08,1628000.0,19778000.0,2000
26747,1038357,2.175265e+09,-29800000.0,2714000.0,-1.552442e+09,2.116044e+09,201988000.0,2.692237e+09,789077000.0,789077000.0,...,59221000.0,846330000.0,7.86746,721944000.0,-566096000.0,789077000.0,3.481314e+09,337308000.0,526832000.0,2000
29450,890908,1.204000e+06,644000.0,-2000.0,5.538000e+06,1.539000e+06,5709000.0,7.148000e+06,8365000.0,8365000.0,...,1164000.0,60070000.0,0.64632,16212000.0,3927000.0,8365000.0,1.551300e+07,566000.0,4720000.0,2000
32744,1038368,1.077080e+08,-1477000.0,-302000.0,1.497400e+07,9.227700e+07,85937000.0,1.364530e+08,29135000.0,-23821000.0,...,15431000.0,27820000.0,-3.39165,189940000.0,12853000.0,-23821000.0,1.655880e+08,931000.0,30555000.0,2000

In [24]:
datum.sort_values(by=['Instrument', 'Year'], inplace=True)
datum

,Instrument,Total Debt,Accounts Payable (CF),Inventories (CF),Retained Earnings (Accumulated Deficit),Net Debt Incl. Pref.Stock & Min.Interest,Total Current Assets,Total Liabilities,Total Equity,Tangible Book Value - Banks,...,Cash and Short Term Investments,Market Value for Company,Tangible Book Value Per Share,Net Sales,Operating Income,Tangible Book Value - Utility,"Total Assets, Reported",Depreciation And Amortization,Total Current Liabilities,Year
72431,1750,2.602240e+08,-25261000.0,-31749000.0,156479000.0,2.257020e+08,4.366560e+08,3.999640e+08,310235000.0,264329000.0,...,34522000.0,1.640000e+08,8.29398,6.387210e+08,-81289000.0,264329000.0,7.101990e+08,NaN,150464000.0,2003
88508,1750,2.569140e+08,-2841000.0,17755000.0,143272000.0,2.277600e+08,3.964120e+08,3.916330e+08,294988000.0,249037000.0,...,29154000.0,4.790900e+08,7.81881,5.998420e+08,908000.0,249037000.0,6.866210e+08,NaN,203575000.0,2004
104585,1750,2.520580e+08,6642000.0,15602000.0,146776000.0,2.183610e+08,4.322040e+08,4.076080e+08,301684000.0,257263000.0,...,33697000.0,4.389800e+08,7.97838,6.444690e+08,20281000.0,257263000.0,7.092920e+08,NaN,131261000.0,2005
120662,1750,2.309040e+08,19244000.0,-12013000.0,162229000.0,1.903960e+08,4.745420e+08,4.174860e+08,314744000.0,270328000.0,...,40508000.0,8.022800e+08,8.29583,7.404270e+08,38479000.0,270328000.0,7.322300e+08,NaN,160025000.0,2006
136739,1750,3.208650e+08,19735000.0,-58297000.0,197392000.0,1.991270e+08,6.244540e+08,5.561020e+08,422717000.0,378285000.0,...,121738000.0,1.079330e+09,10.32043,8.855180e+08,61279000.0,378285000.0,9.788190e+08,NaN,187788000.0,2007
3838,2034,7.608000e+06,4174000.0,694000.0,40863000.0,-7.967000e+06,1.007240e+08,4.241300e+07,73290000.0,63469000.0,...,15575000.0,1.042400e+08,2.87098,2.293290e+08,7336000.0,63469000.0,1.157030e+08,NaN,42413000.0,2003
5048,2034,3.286000e+06,2907000.0,-4597000.0,46142000.0,-1.785400e+07,1.101150e+08,3.895000e+07,84569000.0,76374000.0,...,21140000.0,2.651600e+08,3.27138,2.699610e+08,13027000.0,76374000.0,1.235190e+08,NaN,38950000.0,2004
6258,2034,1.000000e+06,9563000.0,2166000.0,56490000.0,-3.206100e+07,1.329740e+08,4.943100e+07,100266000.0,93386000.0,...,33218000.0,3.023400e+08,3.87205,2.963590e+08,16118000.0,93386000.0,1.496970e+08,NaN,46554000.0,2005
7468,2034,6.260000e+05,-8681000.0,-10188000.0,62864000.0,-2.422100e+07,1.316400e+08,4.137300e+07,107655000.0,102782000.0,...,25018000.0,1.598900e+08,4.23285,3.134310e+08,11590000.0,102782000.0,1.490280e+08,NaN,37391000.0,2006
8678,2034,5.000000e+05,-3962000.0,4909000.0,68464000.0,-3.630900e+07,1.411060e+08,5.153900e+07,115053000.0,109509000.0,...,37041000.0,2.098400e+08,4.51063,2.973280e+08,12429000.0,109509000.0,1.665920e+08,NaN,36399000.0,2007
15938,2034,4.576500e+07,-978000.0,-9926000.0,102344000.0,1.938500e+07,1.919690e+08,1.312770e+08,168003000.0,89257000.0,...,26380000.0,2.743300e+08,3.31355,4.443880e+08,25366000.0,89257000.0,2.992800e+08,NaN,73641000.0,2013
17148,2034,3.206900e+07,-3228000.0,1632000.0,118615000.0,-3.306000e+06,2.183000e+08,1.287900e+08,194640000.0,120283000.0,...,35375000.0,7.036700e+08,4.32191,4.996900e+08,34416000.0,120283000.0,3.234300e+08,NaN,89907000.0,2014
18358,2034,1.055010e+08,5216000.0,-7764000.0,140768000.0,6.185800e+07,2.763540e+08,2.344000e+08,233584000.0,79113000.0,...,43643000.0,6.307100e+08,2.74965,5.101790e+08,44272000.0,79113000.0,4.679840e+08,NaN,118523000.0,2015
19568,2034,1.101570e+08,8133000.0,-229000.0,167208000.0,7.272100e+07,3.103100e+08,2.355630e+08,254211000.0,107344000.0,...,37436000.0,7.959600e+08,3.68285,5.469510e+08,56333000.0,107344000.0,4.897740e+08,4790000.0,125000000.0,2016
20778,2034,1.187890e+08,-8937000.0,-2489000.0,194804000.0,5.108000e+07,3.526610e+08,2.363360e+08,304442000.0,157500000.0,...,67709000.0,6.602300e+08,5.32184,5.585240e+08,58028000.0,157500000.0,5.407780e+08,NaN,98906000.0,2017
1349,2178,9.900000e+06,158037000.0,-13187000.0,23906000.0,-1.423700e+07,2.642250e+08,2.570270e+08,36021000.0,36021000.0,...,24137000.0,5.905000e+07,8.54064,3.995477e+09,7963000.0,36021000.0,2.930480e+08,6071000.0,244787000.0,2001
2559,2178,1.190000e+07,109022000.0,-13978000.0,32198000.0,-2.424000e+07,4.200320e+08,4.037310e+08,44313000.0,44313000.0,...,36140000.0,3.290000e+07,10.50669,7.022160e+09,12861000.0,44313000.0,4.480440e+08,6745000.0,387376000.0,2002
3769,2178,1.247500e+07,-193875000.0,25763000.0,27081000.0,-1.702000e+06,1.993050e+08,1.878310e+08,39196000.0,39196000.0,...,14177000.0,2.214000e+07,9.29344,3.483310e+09,-14265000.0,39196000.0,2.270270e+08,6726000.0,168971000.0,2003
4979,2178,1.147500e+07,-14356000.0,3534000.0,27985000.0,-1.578700e+07,1.794000e+08,1.620200e+08,40100000.0,40100000.0,...,27262000.0,5.715000e+07,9.50778,1.767350e+09,5122000.0,40100000.0,2.021200e+08,5565000.0,148084000.0,2004
6189,2178,1.147500e+07,7947000.0,-1319000.0,30117000.0,-1.686700e+07,1.854230e+08,1.683750e+08,42232000.0,42232000.0,...,28342000.0,7.466000e+07,10.01328,1.720928e+09,9101000.0,42232000.0,2.106070e+08,5164000.0,152665000.0,2005
7399,2178,1.147500e+07,15138000.0,-5072000.0,37460000.0,-8.467000e+06,2.093390e+08,1.892790e+08,49575000.0,49575000.0,...,19942000.0,9.634000e+07,11.75432,2.069087e+09,13779000.0,49575000.0,2.388540e+08,6285000.0,173550000.0,2006
8609,2178,1.147500e+07,53200000.0,-320000.0,53541000.0,-7.342000e+06,2.704500e+08,2.470060e+08,65656000.0,65656000.0,...,18817000.0,1.270000e+08,15.56715,2.364833e+09,25292000.0,65656000.0,3.126620e+08,7060000.0,231129000.0,2007
9819,2178,3.000000e+06,-27682000.0,3742000.0,62253000.0,-1.766800e+07,2.417900e+08,2.149190e+08,74368000.0,74368000.0,...,20668000.0,1.084000e+08,17.63278,2.246603e+09,14967000.0,74368000.0,2.892870e+08,9485000.0,206582000.0,2008
11029,2178,0.000000e+00,66556000.0,-6826000.0,77327000.0,-2.369700e+07,3.118930e+08,2.676330e+08,89442000.0,89442000.0,...,23697000.0,7.171000e+07,21.20685,2.636222e+09,23907000.0,89442000.0,3.570750e+08,11384000.0,261321000.0,2009
12239,2178,0.000000e+00,-137548000.0,569000.0,69646000.0,-1.820800e+07,1.693660e+08,1.291650e+08,81761000.0,81761000.0,...,18208000.0,9.301000e+07,19.38567,4.159672e+09,-11474000.0,81761000.0,2.109260e+08,13373000.0,127807000.0,2010
13449,2178,0.000000e+00,43069000.0,-1053000.0,71686000.0,-1.680600e+07,2.025630e+08,1.656000e+08,83801000.0,83801000.0,...,16806000.0,1.032900e+08,19.86936,1.943128e+09,6401000.0,83801000.0,2.494010e+08,10320000.0,164191000.0,2011
14659,2178,0.000000e+00,40521000.0,669000.0,78040000.0,-2.903200e+07,2.469760e+08,2.111500e+08,90155000.0,90155000.0,...,29032000.0,1.227800e+08,21.37590,2.083781e+09,12425000.0,90155000.0,3.013050e+08,11314000.0,206998000.0,2012
15869,2178,0.000000e+00,47662000.0,-5598000.0,98567000.0,-3.706600e+07,3.049650e+08,2.681580e+08,110682000.0,110682000.0,...,37066000.0,1.479100e+08,26.24289,3.038737e+09,35206000.0,110682000.0,3.788400e+08,15885000.0,256094000.0,2013
17079,2178,0.000000e+00,10474000.0,-9579000.0,123743000.0,-4.723900e+07,3.245560e+08,2.836430e+08,135858000.0,135858000.0,...,47239000.0,2.889100e+08,32.21216,3.376085e+09,43956000.0,135858000.0,4.195010e+08,20714000.0,266082000.0,2014
18289,2178,0.000000e+00,7809000.0,606000.0,142570000.0,-7.443800e+07,3.517300e+08,2.933970e+08,154685000.0,154685000.0,...,74438000.0,2.106700e+08,36.67607,3.945969e+09,34376000.0,154685000.0,4.480820e+08,22275000.0,272169000.0,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129471,1678531,8.791000e+07,1062000.0,-127000.0,127611000.0,1.126280e+08,7.331800e+07,1.710060e+08,254149000.0,-11827000.0,...,14992000.0,NaN,-0.40200,3.266790e+08,125000000.0,-11827000.0,4.251550e+08,12790000.0,17016000.0,2006
145548,1678531,1.082620e+08,1923000.0,-438000.0,162762000.0,1.350370e+08,8.767200e+07,2.331980e+08,294618000.0,-50652000.0,...,20496000.0,NaN,-1.70611,3.784510e+08,139165000.0,-50652000.0,5.278160e+08,14940000.0,26600000.0,2007
16053,1690769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
17263,1690769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
18473,1690769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
19683,1690769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016
20893,1690769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
149562,1694426,2.687550e+08,88100000.0,11100000.0,78749000.0,1.796010e+08,2.518210e+08,4.862900e+08,119870000.0,55610000.0,...,89154000.0,8.340900e+08,1.41178,1.931900e+09,116700000.0,55610000.0,6.061600e+08,15100000.0,175814000.0,2007
165639,1694426,2.866000e+08,37100000.0,-37200000.0,169800000.0,1.118000e+08,4.106000e+08,5.672000e+08,382200000.0,289300000.0,...,174800000.0,1.085680e+09,5.65703,3.115400e+09,152800000.0,289300000.0,9.494000e+08,21800000.0,230900000.0,2008
181716,1694426,3.552000e+08,84700000.0,-19700000.0,237600000.0,2.058000e+08,4.753000e+08,7.318000e+08,512500000.0,415200000.0,...,149400000.0,2.839700e+08,7.73666,3.994200e+09,155000000.0,415200000.0,1.244300e+09,32100000.0,305000000.0,2009
197793,1694426,2.860000e+08,-193200000.0,58900000.0,256100000.0,2.707000e+08,1.940000e+08,4.834000e+08,533800000.0,444600000.0,...,15300000.0,3.657000e+08,8.28209,4.723700e+09,73700000.0,444600000.0,1.017200e+09,41300000.0,186200000.0,2010
213870,1694426,3.171000e+08,137200000.0,-46900000.0,248700000.0,2.487000e+08,3.116000e+08,6.920000e+08,531000000.0,450100000.0,...,68400000.0,4.020400e+08,8.38166,2.666700e+09,31400000.0,450100000.0,1.223000e+09,52400000.0,322200000.0,2011
229947,1694426,2.958000e+08,38900000.0,20900000.0,155300000.0,2.467000e+08,2.994000e+08,7.013000e+08,443300000.0,363500000.0,...,49100000.0,6.619700e+08,6.68159,3.755600e+09,-50800000.0,363500000.0,1.144600e+09,61100000.0,292500000.0,2012
246024,1694426,4.326000e+08,65300000.0,-166900000.0,294100000.0,2.069000e+08,1.050600e+09,1.577200e+09,653400000.0,566200000.0,...,225900000.0,1.509570e+09,9.75594,7.198200e+09,299000000.0,566200000.0,2.230600e+09,74100000.0,994700000.0,2013
262101,1694426,3.622000e+08,38900000.0,46000000.0,531400000.0,-6.080000e+07,1.359700e+09,1.724400e+09,899300000.0,809900000.0,...,601700000.0,2.069480e+09,13.58447,8.726700e+09,473100000.0,809900000.0,2.623700e+09,82500000.0,999100000.0,2014
16006,1720201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
17216,1720201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
18426,1720201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
19636,1720201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016
20846,1720201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
73718,1733998,5.266680e+08,-40000000.0,-2454000.0,147950000.0,5.502280e+08,2.103340e+08,9.328610e+08,502161000.0,468161000.0,...,10440000.0,6.892700e+08,18.55715,NaN,110211000.0,468161000.0,1.435022e+09,49640000.0,273582000.0,2003
89795,1733998,5.357470e+08,3738000.0,-8693000.0,157136000.0,5.366690e+08,1.932970e+08,9.766350e+08,490642000.0,482392000.0,...,7328000.0,7.951600e+08,18.85352,NaN,116258000.0,482392000.0,1.467277e+09,52090000.0,205007000.0,2004
105872,1733998,5.855190e+08,11593000.0,7171000.0,170053000.0,5.808130e+08,1.958340e+08,1.079063e+09,506316000.0,506316000.0,...,4706000.0,9.126400e+08,19.52024,NaN,102272000.0,506316000.0,1.585379e+09,54249000.0,214421000.0,2005
121949,1733998,6.015270e+08,16449000.0,-15618000.0,183932000.0,5.962790e+08,2.371170e+08,1.163678e+09,568517000.0,568517000.0,...,5248000.0,9.416600e+08,20.63828,NaN,110026000.0,568517000.0,1.732195e+09,57371000.0,267285000.0,2006
138026,1733998,6.562000e+08,32809000.0,-19684000.0,205687000.0,6.490570e+08,4.913480e+08,1.455373e+09,586931000.0,586931000.0,...,7143000.0,1.167310e+09,21.28158,NaN,126947000.0,586931000.0,2.042304e+09,61645000.0,479305000.0,2007
16144,1735828,3.370000e+08,2655000.0,NaN,NaN,3.339200e+08,5.978500e+07,5.551530e+08,488335000.0,484281000.0,...,3151000.0,1.351820e+09,10.13105,3.368850e+08,84495000.0,484281000.0,1.043488e+09,88178000.0,97450000.0,2013
17354,1735828,7.758380e+08,-1464000.0,NaN,NaN,7.724260e+08,8.791000e+07,1.019719e+09,670280000.0,666697000.0,...,3509000.0,1.619580e+09,11.68845,3.464600e+08,51491000.0,666697000.0,1.689999e+09,102144000.0,103723000.0,2014
18564,1735828,8.786930e+08,4194000.0,NaN,NaN,8.761830e+08,7.469900e+07,1.149437e+09,510396000.0,507330000.0,...,2584000.0,7.905600e+08,8.85701,4.854890e+08,27644000.0,507330000.0,1.659833e+09,158415000.0,93890000.0,2015
19774,1735828,9.388760e+08,-3228000.0,NaN,NaN,1.167657e+09,1.922540e+08,1.261401e+09,637205000.0,405191000.0,...,725000.0,1.216300e+08,5.87994,5.322990e+08,-356937000.0,405191000.0,1.898606e+09,173686000.0,97576000.0,2016
20984,1735828,1.427614e+09,10794000.0,NaN,NaN,1.654928e+09,1.294590e+08,1.792797e+09,-179677000.0,-411061000.0,...,2006000.0,1.538000e+08,-5.96173,3.387790e+08,-725697000.0,-411061000.0,1.613120e+09,177258000.0,81093000.0,2017

In [25]:
# the dataframe with no extra double row
datum.to_csv('datum.csv', index=False)