In [1]:
import pandas as pd

## Read Word-Distance CSV

In [2]:
word_dist = pd.read_csv('word_distances_200.csv')

word_dist.head()

,CIK,Year,d_income,d_loss,d_increase,d_decrease,d_strong,d_discontinued,d_international,d_focus,d_repurchase,d_service,d_goodwill,d_reset,d_expenditure,d_stress,d_exit,d_tranche,d_accordingly
0,73887,2013,0.542590,0.366890,0.469616,0.480060,0.259568,0.330127,0.236790,0.238665,0.418506,0.287535,0.303027,0.237451,0.406020,0.187593,0.204314,0.314730,0.263849
1,865415,2013,0.518870,0.344929,0.463734,0.470345,0.280670,0.345577,0.251816,0.262614,0.463203,0.324465,0.316390,0.253559,0.407702,0.207744,0.194877,0.353913,0.300055
2,1495479,2013,0.525458,0.332708,0.490876,0.498556,0.247756,0.324568,0.219694,0.233236,0.387581,0.309420,0.292899,0.214094,0.426564,0.194294,0.196470,0.298803,0.264974
3,89270,2013,0.516563,0.355605,0.516655,0.546978,0.267709,0.385234,0.242831,0.245901,0.430440,0.314230,0.288861,0.212884,0.405855,0.186739,0.170780,0.313238,0.272657
4,49754,2013,0.534632,0.326196,0.459805,0.475629,0.257686,0.352222,0.242155,0.259083,0.453057,0.333016,0.318762,0.233707,0.394037,0.209957,0.221210,0.329416,0.275069

In [3]:
word_dist.fillna(0, inplace=True)
word_dist.head()

,CIK,Year,d_income,d_loss,d_increase,d_decrease,d_strong,d_discontinued,d_international,d_focus,d_repurchase,d_service,d_goodwill,d_reset,d_expenditure,d_stress,d_exit,d_tranche,d_accordingly
0,73887,2013,0.542590,0.366890,0.469616,0.480060,0.259568,0.330127,0.236790,0.238665,0.418506,0.287535,0.303027,0.237451,0.406020,0.187593,0.204314,0.314730,0.263849
1,865415,2013,0.518870,0.344929,0.463734,0.470345,0.280670,0.345577,0.251816,0.262614,0.463203,0.324465,0.316390,0.253559,0.407702,0.207744,0.194877,0.353913,0.300055
2,1495479,2013,0.525458,0.332708,0.490876,0.498556,0.247756,0.324568,0.219694,0.233236,0.387581,0.309420,0.292899,0.214094,0.426564,0.194294,0.196470,0.298803,0.264974
3,89270,2013,0.516563,0.355605,0.516655,0.546978,0.267709,0.385234,0.242831,0.245901,0.430440,0.314230,0.288861,0.212884,0.405855,0.186739,0.170780,0.313238,0.272657
4,49754,2013,0.534632,0.326196,0.459805,0.475629,0.257686,0.352222,0.242155,0.259083,0.453057,0.333016,0.318762,0.233707,0.394037,0.209957,0.221210,0.329416,0.275069

In [4]:
word_dist.shape

(10123, 19)

## Read Financial Factors CSV

In [5]:
fin_fact = pd.read_csv('fin_facts_fill_norm.csv')
fin_fact.head()

,Instrument,Total Debt,Accounts Payable (CF),Inventories (CF),Retained Earnings (Accumulated Deficit),Net Debt Incl. Pref.Stock & Min.Interest,Total Current Assets,Total Liabilities,Total Equity,Tangible Book Value - Insurance,...,Cash and Short Term Investments,Market Value for Company,Tangible Book Value Per Share,Net Sales,Operating Income,Tangible Book Value - Utility,"Total Assets, Reported",Total Current Liabilities,Year,Bankrupt
0,1750,0.000005,-0.025690,-0.041836,-0.997354,-0.998423,0.000015,0.000005,-0.998949,-0.998920,...,0.000003,7.305217e-07,-0.729259,-0.999982,-0.979199,-0.998920,0.000005,0.000007,2003,0
1,1750,0.000005,-0.025680,-0.041751,-0.997355,-0.998422,0.000014,0.000005,-0.998949,-0.998920,...,0.000003,2.134059e-06,-0.729259,-0.999983,-0.979193,-0.998920,0.000005,0.000009,2004,0
2,1750,0.000005,-0.025676,-0.041755,-0.997355,-0.998423,0.000015,0.000005,-0.998949,-0.998920,...,0.000003,1.955393e-06,-0.729259,-0.999982,-0.979192,-0.998920,0.000005,0.000006,2005,0
3,1750,0.000004,-0.025671,-0.041802,-0.997354,-0.998424,0.000017,0.000005,-0.998949,-0.998920,...,0.000004,3.573676e-06,-0.729259,-0.999979,-0.979190,-0.998920,0.000006,0.000007,2006,0
4,1750,0.000006,-0.025670,-0.041881,-0.997353,-0.998424,0.000022,0.000007,-0.998946,-0.998917,...,0.000012,4.807768e-06,-0.729259,-0.999975,-0.979188,-0.998917,0.000007,0.000008,2007,0

In [6]:
fin_fact.shape

(16445, 22)

In [7]:
fin_fact.rename(columns={'Instrument': 'CIK'}, inplace=True)
fin_fact.head()

,CIK,Total Debt,Accounts Payable (CF),Inventories (CF),Retained Earnings (Accumulated Deficit),Net Debt Incl. Pref.Stock & Min.Interest,Total Current Assets,Total Liabilities,Total Equity,Tangible Book Value - Insurance,...,Cash and Short Term Investments,Market Value for Company,Tangible Book Value Per Share,Net Sales,Operating Income,Tangible Book Value - Utility,"Total Assets, Reported",Total Current Liabilities,Year,Bankrupt
0,1750,0.000005,-0.025690,-0.041836,-0.997354,-0.998423,0.000015,0.000005,-0.998949,-0.998920,...,0.000003,7.305217e-07,-0.729259,-0.999982,-0.979199,-0.998920,0.000005,0.000007,2003,0
1,1750,0.000005,-0.025680,-0.041751,-0.997355,-0.998422,0.000014,0.000005,-0.998949,-0.998920,...,0.000003,2.134059e-06,-0.729259,-0.999983,-0.979193,-0.998920,0.000005,0.000009,2004,0
2,1750,0.000005,-0.025676,-0.041755,-0.997355,-0.998423,0.000015,0.000005,-0.998949,-0.998920,...,0.000003,1.955393e-06,-0.729259,-0.999982,-0.979192,-0.998920,0.000005,0.000006,2005,0
3,1750,0.000004,-0.025671,-0.041802,-0.997354,-0.998424,0.000017,0.000005,-0.998949,-0.998920,...,0.000004,3.573676e-06,-0.729259,-0.999979,-0.979190,-0.998920,0.000006,0.000007,2006,0
4,1750,0.000006,-0.025670,-0.041881,-0.997353,-0.998424,0.000022,0.000007,-0.998946,-0.998917,...,0.000012,4.807768e-06,-0.729259,-0.999975,-0.979188,-0.998917,0.000007,0.000008,2007,0

## Check Two Dataset CIK Lists

In [8]:
print('The unique number of companies in the financial factors dataset:')
print(len(set(fin_fact.CIK.to_list())))

print('\nThe unique number of companies in the word-distance dataset:')
print(len(set(word_dist.CIK.to_list())))

The unique number of companies in the financial factors dataset:
2107

The unique number of companies in the word-distance dataset:
1699

## Merging

In [9]:
fin_fact.set_index(['CIK', 'Year'], inplace=True)
word_dist.set_index(['CIK', 'Year'], inplace=True)

data = pd.concat([fin_fact, word_dist], axis=1)

In [12]:
data.head()

           Total Debt  Accounts Payable (CF)  Inventories (CF)  \
CIK  Year
1750 2003    0.000005              -0.025690         -0.041836
     2004    0.000005              -0.025680         -0.041751
     2005    0.000005              -0.025676         -0.041755
     2006    0.000004              -0.025671         -0.041802
     2007    0.000006              -0.025670         -0.041881

           Retained Earnings (Accumulated Deficit)  \
CIK  Year
1750 2003                                -0.997354
     2004                                -0.997355
     2005                                -0.997355
     2006                                -0.997354
     2007                                -0.997353

           Net Debt Incl. Pref.Stock & Min.Interest  Total Current Assets  \
CIK  Year
1750 2003                                 -0.998423              0.000015
     2004                                 -0.998422              0.000014
     2005                                 -0.998423              0.000015
     2006                                 -0.998424              0.000017
     2007                                 -0.998424              0.000022

           Total Liabilities  Total Equity  Tangible Book Value - Insurance  \
CIK  Year
1750 2003           0.000005     -0.998949                        -0.998920
     2004           0.000005     -0.998949                        -0.998920
     2005           0.000005     -0.998949                        -0.998920
     2006           0.000005     -0.998949                        -0.998920
     2007           0.000007     -0.998946                        -0.998917

           Net Income/Starting Line, Cumulative  ...  d_focus  d_repurchase  \
CIK  Year                                        ...
1750 2003                             -0.589747  ...      0.0           0.0
     2004                             -0.589743  ...      0.0           0.0
     2005                             -0.589741  ...      0.0           0.0
     2006                             -0.589740  ...      0.0           0.0
     2007                             -0.589738  ...      0.0           0.0

           d_service  d_goodwill  d_reset  d_expenditure  d_stress  d_exit  \
CIK  Year
1750 2003        0.0         0.0      0.0            0.0       0.0     0.0
     2004        0.0         0.0      0.0            0.0       0.0     0.0
     2005        0.0         0.0      0.0            0.0       0.0     0.0
     2006        0.0         0.0      0.0            0.0       0.0     0.0
     2007        0.0         0.0      0.0            0.0       0.0     0.0

           d_tranche  d_accordingly
CIK  Year
1750 2003        0.0            0.0
     2004        0.0            0.0
     2005        0.0            0.0
     2006        0.0            0.0
     2007        0.0            0.0

[5 rows x 37 columns]

In [13]:
data.fillna(0, inplace=True)
data.head(20)

             Total Debt  Accounts Payable (CF)  Inventories (CF)  \
CIK  Year
1750 2003  4.889284e-06              -0.025690         -0.041836
     2004  4.827093e-06              -0.025680         -0.041751
     2005  4.735855e-06              -0.025676         -0.041755
     2006  4.338398e-06              -0.025671         -0.041802
     2007  6.028652e-06              -0.025670         -0.041881
2034 2003  1.429448e-07              -0.025677         -0.041781
     2004  6.173983e-08              -0.025678         -0.041790
     2005  1.878875e-08              -0.025675         -0.041778
     2006  1.176176e-08              -0.025683         -0.041799
     2007  9.394375e-09              -0.025681         -0.041773
     2013  8.598672e-07              -0.025680         -0.041799
     2014  6.025364e-07              -0.025681         -0.041779
     2015  1.982232e-06              -0.025677         -0.041795
     2016  2.069712e-06              -0.025676         -0.041782
     2017  2.231897e-06              -0.025683         -0.041786
2178 2001  1.860086e-07              -0.025609         -0.041804
     2002  2.235861e-07              -0.025631         -0.041806
     2003  2.343897e-07              -0.025765         -0.041738
     2004  2.156009e-07              -0.025685         -0.041776
     2005  2.156009e-07              -0.025676         -0.041784

           Retained Earnings (Accumulated Deficit)  \
CIK  Year
1750 2003                                -0.997354
     2004                                -0.997355
     2005                                -0.997355
     2006                                -0.997354
     2007                                -0.997353
2034 2003                                -0.997359
     2004                                -0.997359
     2005                                -0.997358
     2006                                -0.997358
     2007                                -0.997358
     2013                                -0.997356
     2014                                -0.997356
     2015                                -0.997355
     2016                                -0.997354
     2017                                -0.997353
2178 2001                                -0.997359
     2002                                -0.997359
     2003                                -0.997359
     2004                                -0.997359
     2005                                -0.997359

           Net Debt Incl. Pref.Stock & Min.Interest  Total Current Assets  \
CIK  Year
1750 2003                                 -0.998423              0.000015
     2004                                 -0.998422              0.000014
     2005                                 -0.998423              0.000015
     2006                                 -0.998424              0.000017
     2007                                 -0.998424              0.000022
2034 2003                                 -0.998432              0.000004
     2004                                 -0.998433              0.000004
     2005                                 -0.998433              0.000005
     2006                                 -0.998433              0.000005
     2007                                 -0.998434              0.000005
     2013                                 -0.998431              0.000007
     2014                                 -0.998432              0.000008
     2015                                 -0.998429              0.000010
     2016                                 -0.998429              0.000011
     2017                                 -0.998430              0.000012
2178 2001                                 -0.998433              0.000009
     2002                                 -0.998433              0.000015
     2003                                 -0.998432              0.000007
     2004                                 -0.998433              0.000006
     2005                                 -0.998433              0.000006

           Total Liabilities  Total Equity  Tangible Book Value - Insurance  \
CIK  Year
1750 2003       5.022198e-06     -0.998949                        -0.998920
     2004       4.917589e-06     -0.998949                        -0.998920
     2005       5.118181e-06     -0.998949                        -0.998920
     2006       5.242215e-06     -0.998949                        -0.998920
     2007       6.982764e-06     -0.998946                        -0.998917
2034 2003       5.325641e-07     -0.998955                        -0.998926
     2004       4.890805e-07     -0.998955                        -0.998925
     2005       6.206865e-07     -0.998955                        -0.998925
     2006       5.195052e-07     -0.998954                        -0.998925
     2007       6.471559e-07     -0.998954                        -0.998924
     2013       1.648396e-06     -0.998953                        -0.998925
     2014       1.617168e-06     -0.998952                        -0.998924
     2015       2.943273e-06     -0.998951                        -0.998925
     2016       2.957876e-06     -0.998950                        -0.998924
     2017       2.967582e-06     -0.998949                        -0.998923
2178 2001       3.227392e-06     -0.998956                        -0.998926
     2002       5.069499e-06     -0.998956                        -0.998926
     2003       2.358523e-06     -0.998956                        -0.998926
     2004       2.034424e-06     -0.998956                        -0.998926
     2005       2.114222e-06     -0.998956                        -0.998926

           Net Income/Starting Line, Cumulative  ...   d_focus  d_repurchase  \
CIK  Year                                        ...
1750 2003                             -0.589747  ...  0.000000      0.000000
     2004                             -0.589743  ...  0.000000      0.000000
     2005                             -0.589741  ...  0.000000      0.000000
     2006                             -0.589740  ...  0.000000      0.000000
     2007                             -0.589738  ...  0.000000      0.000000
2034 2003                             -0.589741  ...  0.000000      0.000000
     2004                             -0.589741  ...  0.000000      0.000000
     2005                             -0.589740  ...  0.000000      0.000000
     2006                             -0.589740  ...  0.000000      0.000000
     2007                             -0.589740  ...  0.000000      0.000000
     2013                             -0.589740  ...  0.000000      0.000000
     2014                             -0.589739  ...  0.000000      0.000000
     2015                             -0.589738  ...  0.000000      0.000000
     2016                             -0.589738  ...  0.000000      0.000000
     2017                             -0.589738  ...  0.000000      0.000000
2178 2001                             -0.589741  ...  0.000000      0.000000
     2002                             -0.589740  ...  0.000000      0.000000
     2003                             -0.589742  ...  0.252844      0.428625
     2004                             -0.589741  ...  0.256376      0.428781
     2005                             -0.589741  ...  0.065945      0.161882

           d_service  d_goodwill   d_reset  d_expenditure  d_stress    d_exit  \
CIK  Year
1750 2003   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2004   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2005   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2006   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2007   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
2034 2003   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2004   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2005   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2006   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2007   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2013   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2014   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2015   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2016   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2017   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
2178 2001   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2002   0.000000    0.000000  0.000000       0.000000  0.000000  0.000000
     2003   0.307050    0.285348  0.221353       0.384614  0.207751  0.195255
     2004   0.311134    0.291284  0.227605       0.388935  0.206180  0.193865
     2005   0.058350    0.089760  0.194792       0.144917  0.059821  0.129431

           d_tranche  d_accordingly
CIK  Year
1750 2003   0.000000       0.000000
     2004   0.000000       0.000000
     2005   0.000000       0.000000
     2006   0.000000       0.000000
     2007   0.000000       0.000000
2034 2003   0.000000       0.000000
     2004   0.000000       0.000000
     2005   0.000000       0.000000
     2006   0.000000       0.000000
     2007   0.000000       0.000000
     2013   0.000000       0.000000
     2014   0.000000       0.000000
     2015   0.000000       0.000000
     2016   0.000000       0.000000
     2017   0.000000       0.000000
2178 2001   0.000000       0.000000
     2002   0.000000       0.000000
     2003   0.321731       0.296390
     2004   0.330473       0.298616
     2005   0.128140       0.166040

[20 rows x 37 columns]

## Write the CSV File

In [14]:
data.to_csv('data.csv', index=False)